// Kratos Demo Data - God of War themed entries
import type { Entry } from "../airtable"

export function getKratosDemoData(): Entry[] {
  return [
    // Week 1 - Training Atreus, Patience Struggles
    {
      id: "kratos-1",
      name: "The Boy Must Learn",
      type: "Family",
      date: "2026-01-08",
      timestamp: "2026-01-08T06:00:00Z",
      text: "Atreus missed his mark again today. Three arrows, three misses. I felt the rage building but held it back. Faye would want me to be patient. The boy is not ready for what lies ahead, but neither was I at his age.",
      userId: "demo-kratos",
      inferredMode: "Determined",
      inferredEnergy: "Moderate",
      energyShape: "Heavy",
      contradiction: "Action vs. Fear",
      snapshot: "Training frustration",
      loops: "Patience struggles",
      nextAction: "Continue training tomorrow",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Struggling with patience while training Atreus",
      actionableInsightsAI: "Remember Faye's wisdom about patience",
      entryLengthWords: 52,
      daysSinceEntry: 0,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["fatherhood", "patience", "training"],
      createdTime: "2026-01-08T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-2",
      name: "Faye's Ashes Weigh Heavy",
      type: "Emotional",
      date: "2026-01-08",
      timestamp: "2026-01-08T12:00:00Z",
      text: "I carry her ashes and her final wish. The highest peak in all the realms. Why did she choose this path for us? She knew what I was, what I've done. Yet she trusted me with our son. I will not fail her.",
      userId: "demo-kratos",
      inferredMode: "Grieving",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Past vs. Present",
      snapshot: "Mourning reflection",
      loops: "Grief patterns",
      nextAction: "Honor her wish",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Reflecting on Faye's death and final wish",
      actionableInsightsAI: "Channel grief into purpose",
      entryLengthWords: 55,
      daysSinceEntry: 1,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["grief", "purpose", "love"],
      createdTime: "2026-01-08T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-3",
      name: "Sparta Haunts My Dreams",
      type: "Reflection",
      date: "2026-01-08",
      timestamp: "2026-01-08T18:00:00Z",
      text: "I dreamt of the flames again. The screams. My hands red with the blood of those I loved. Atreus cannot know what his father truly is. The Ghost of Sparta must remain buried. This new life is all that matters.",
      userId: "demo-kratos",
      inferredMode: "Haunted",
      inferredEnergy: "Drained",
      energyShape: "Chaotic",
      contradiction: "Past vs. Present",
      snapshot: "Nightmare aftermath",
      loops: "PTSD patterns",
      nextAction: "Focus on present",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Haunted by nightmares of past violence",
      actionableInsightsAI: "The past does not define the future",
      entryLengthWords: 52,
      daysSinceEntry: 1,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["nightmares", "guilt", "redemption"],
      createdTime: "2026-01-08T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-4",
      name: "The Stranger's Visit",
      type: "Work",
      date: "2026-01-07",
      timestamp: "2026-01-07T22:00:00Z",
      text: "A stranger came to our door today. He knew what I am. The fight was... unexpected. He felt no pain. This realm has gods too, it seems. They will come for us. The boy and I must leave. Now.",
      userId: "demo-kratos",
      inferredMode: "Alert",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Action vs. Fear",
      snapshot: "Combat encounter",
      loops: "",
      nextAction: "Begin the journey",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Confronted by mysterious stranger with godly powers",
      actionableInsightsAI: "Prepare for threats from Norse pantheon",
      entryLengthWords: 50,
      daysSinceEntry: 2,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["danger", "gods", "protection"],
      createdTime: "2026-01-07T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-5",
      name: "Teaching the Boy to Hunt",
      type: "Family",
      date: "2026-01-07",
      timestamp: "2026-01-07T06:00:00Z",
      text: "Took Atreus hunting before dawn. He is eager but unfocused. He speaks of wanting to make me proud. I do not know how to tell him that surviving is enough. Pride is a luxury I cannot afford.",
      userId: "demo-kratos",
      inferredMode: "Conflicted",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Closeness vs. Distance",
      snapshot: "Father-son moment",
      loops: "Emotional distance",
      nextAction: "Show more presence",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Struggling to connect emotionally with Atreus",
      actionableInsightsAI: "Survival mindset may harm relationship",
      entryLengthWords: 48,
      daysSinceEntry: 2,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["fatherhood", "connection", "survival"],
      createdTime: "2026-01-07T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-6",
      name: "The Axe Feels Different Now",
      type: "Reflection",
      date: "2026-01-07",
      timestamp: "2026-01-07T12:00:00Z",
      text: "Faye's axe. Leviathan. It sings in my hands like the Blades never did. Cold where they burned. It does not demand rage - it channels purpose. Perhaps that was her final gift. A weapon that heals rather than consumes.",
      userId: "demo-kratos",
      inferredMode: "Contemplative",
      inferredEnergy: "Balanced",
      energyShape: "Flowing",
      contradiction: "Past vs. Present",
      snapshot: "Weapon reflection",
      loops: "",
      nextAction: "Honor the gift",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Finding meaning in Faye's axe versus old weapons",
      actionableInsightsAI: "New tools can represent new paths",
      entryLengthWords: 50,
      daysSinceEntry: 3,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["change", "weapons", "meaning"],
      createdTime: "2026-01-07T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-7",
      name: "Atreus Asked About His Mother",
      type: "Emotional",
      date: "2026-01-06",
      timestamp: "2026-01-06T18:00:00Z",
      text: "The boy asked what Faye was like before he was born. I had no words. She was... everything I was not. Light where I brought darkness. Patient where I knew only war. How do I explain love to a child when I barely understood it myself?",
      userId: "demo-kratos",
      inferredMode: "Vulnerable",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Closeness vs. Distance",
      snapshot: "Difficult conversation",
      loops: "Emotional avoidance",
      nextAction: "Try to share more",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Struggling to describe Faye to Atreus",
      actionableInsightsAI: "Vulnerability with son strengthens bond",
      entryLengthWords: 55,
      daysSinceEntry: 3,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["grief", "communication", "love"],
      createdTime: "2026-01-06T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    // Week 2 - Journey Begins, Alfheim
    {
      id: "kratos-8",
      name: "Leaving Home Behind",
      type: "Work",
      date: "2026-01-06",
      timestamp: "2026-01-06T22:00:00Z",
      text: "We burned the cabin. No turning back now. Atreus looked back three times. I did not. Everything I need walks beside me. The mountain awaits. Faye's final wish will be honored.",
      userId: "demo-kratos",
      inferredMode: "Resolute",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Past vs. Present",
      snapshot: "Journey begins",
      loops: "",
      nextAction: "Move forward",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Beginning journey after burning cabin",
      actionableInsightsAI: "Sometimes we must destroy to rebuild",
      entryLengthWords: 42,
      daysSinceEntry: 4,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["journey", "change", "commitment"],
      createdTime: "2026-01-06T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-9",
      name: "The Witch in the Woods",
      type: "Cognitive",
      date: "2026-01-06",
      timestamp: "2026-01-06T06:00:00Z",
      text: "Met a woman who healed the boy's sickness. She knows more than she reveals. Speaks in riddles. Reminds me of the Oracle, but warmer. I do not trust her fully, but her magic saved Atreus. That earns... respect.",
      userId: "demo-kratos",
      inferredMode: "Wary",
      inferredEnergy: "Moderate",
      energyShape: "Uneven",
      contradiction: "Logic vs. Faith",
      snapshot: "New ally assessment",
      loops: "Trust issues",
      nextAction: "Watch carefully",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Evaluating mysterious healer who saved Atreus",
      actionableInsightsAI: "Gratitude can coexist with caution",
      entryLengthWords: 48,
      daysSinceEntry: 4,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["trust", "magic", "allies"],
      createdTime: "2026-01-06T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-10",
      name: "Alfheim's Light",
      type: "Health",
      date: "2026-01-05",
      timestamp: "2026-01-05T12:00:00Z",
      text: "The Light of Alfheim. To retrieve it, I walked in complete darkness. Saw visions. Faye. Atreus as a man. My past sins made manifest. When I emerged, Atreus said I was gone for hours. It felt like seconds. And lifetimes.",
      userId: "demo-kratos",
      inferredMode: "Shaken",
      inferredEnergy: "Drained",
      energyShape: "Chaotic",
      contradiction: "Past vs. Present",
      snapshot: "Mystical experience",
      loops: "Trauma processing",
      nextAction: "Reflect on visions",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Disorienting mystical experience in Alfheim",
      actionableInsightsAI: "Visions may contain important truths",
      entryLengthWords: 52,
      daysSinceEntry: 5,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["visions", "mysticism", "time"],
      createdTime: "2026-01-05T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-11",
      name: "The Boy Doubts Me",
      type: "Family",
      date: "2026-01-05",
      timestamp: "2026-01-05T18:00:00Z",
      text: "Atreus questioned my choices tonight. Said I push him too hard. That I treat him like a soldier, not a son. His words cut deeper than any blade. He is right. I know nothing else. But I must learn.",
      userId: "demo-kratos",
      inferredMode: "Regretful",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Growth vs. Comfort",
      snapshot: "Parenting confrontation",
      loops: "Harsh parenting",
      nextAction: "Change approach",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Atreus confronts harsh parenting style",
      actionableInsightsAI: "Children's feedback reveals blind spots",
      entryLengthWords: 50,
      daysSinceEntry: 5,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["parenting", "criticism", "growth"],
      createdTime: "2026-01-05T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-12",
      name: "A Moment of Praise",
      type: "Family",
      date: "2026-01-05",
      timestamp: "2026-01-05T22:00:00Z",
      text: "The boy made a clean shot today. Through three Draugr in a single arrow line. I said 'Good.' He smiled. Such a small word to mean so much. Faye would have said more. But for now, 'good' was all I had.",
      userId: "demo-kratos",
      inferredMode: "Proud",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Closeness vs. Distance",
      snapshot: "Small victory",
      loops: "",
      nextAction: "Praise more often",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Small moment of praise had big impact",
      actionableInsightsAI: "Small words of affirmation matter greatly",
      entryLengthWords: 52,
      daysSinceEntry: 6,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["praise", "progress", "connection"],
      createdTime: "2026-01-05T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-13",
      name: "Mimir's Stories",
      type: "Cognitive",
      date: "2026-01-04",
      timestamp: "2026-01-04T06:00:00Z",
      text: "The head talks. Constantly. Yet his stories of the Norse gods are... useful. Atreus listens with wonder. I listen for weaknesses. Thor. Odin. Baldur. They all have faults. Information is another weapon.",
      userId: "demo-kratos",
      inferredMode: "Strategic",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Logic vs. Faith",
      snapshot: "Gathering intel",
      loops: "",
      nextAction: "Learn enemy weaknesses",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Using Mimir's tales to understand enemies",
      actionableInsightsAI: "Stories contain tactical knowledge",
      entryLengthWords: 46,
      daysSinceEntry: 6,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["strategy", "knowledge", "gods"],
      createdTime: "2026-01-04T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-14",
      name: "Week One Summary",
      type: "Reflection",
      date: "2026-01-04",
      timestamp: "2026-01-04T12:00:00Z",
      text: "One week since we left home. The boy grows stronger each day. So does his tongue. We have traversed realms I never knew existed. Faced creatures of nightmare. And somehow, we still breathe. The mountain grows closer.",
      userId: "demo-kratos",
      inferredMode: "Reflective",
      inferredEnergy: "Balanced",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Weekly reflection",
      loops: "",
      nextAction: "Continue forward",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "First week of journey progress",
      actionableInsightsAI: "Acknowledge progress made",
      entryLengthWords: 46,
      daysSinceEntry: 7,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["progress", "journey", "survival"],
      createdTime: "2026-01-04T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 3 - Confronting Past, Teaching About Death
    {
      id: "kratos-15",
      name: "The Blades Call to Me",
      type: "Emotional",
      date: "2026-01-04",
      timestamp: "2026-01-04T18:00:00Z",
      text: "Could not sleep. Found myself standing before the hidden chains. The Blades of Chaos. Buried but not forgotten. They whisper of old glories. Old sins. Athena's voice echoes still. I am NOT that monster anymore.",
      userId: "demo-kratos",
      inferredMode: "Tormented",
      inferredEnergy: "Low",
      energyShape: "Chaotic",
      contradiction: "Past vs. Present",
      snapshot: "Past calling",
      loops: "Identity struggle",
      nextAction: "Resist the pull",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Wrestling with temptation of old weapons",
      actionableInsightsAI: "Past identities can resurface under stress",
      entryLengthWords: 50,
      daysSinceEntry: 8,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["temptation", "identity", "past"],
      createdTime: "2026-01-04T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-16",
      name: "Atreus Killed His First Enemy",
      type: "Family",
      date: "2026-01-03",
      timestamp: "2026-01-03T22:00:00Z",
      text: "A Draugr had me pinned. Atreus drove his knife through its skull. Saved my life. The look in his eyes after - fear, pride, horror all at once. I know that look. I've worn it. How do I protect him from becoming me?",
      userId: "demo-kratos",
      inferredMode: "Worried",
      inferredEnergy: "Moderate",
      energyShape: "Heavy",
      contradiction: "Action vs. Fear",
      snapshot: "First kill moment",
      loops: "Generational trauma",
      nextAction: "Talk to him tonight",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Atreus's first kill brings complex emotions",
      actionableInsightsAI: "Address trauma before it takes root",
      entryLengthWords: 52,
      daysSinceEntry: 8,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["violence", "innocence", "protection"],
      createdTime: "2026-01-03T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-17",
      name: "Teaching Him About Death",
      type: "Cognitive",
      date: "2026-01-03",
      timestamp: "2026-01-03T06:00:00Z",
      text: "We burned the bodies of our enemies tonight. Atreus asked why. I told him even enemies deserve respect in death. He asked if I've killed many. I said yes. He asked if it gets easier. I could not lie. It does. And that is the danger.",
      userId: "demo-kratos",
      inferredMode: "Somber",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Justice vs. Mercy",
      snapshot: "Death lesson",
      loops: "",
      nextAction: "Continue honest talks",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Honest conversation about killing",
      actionableInsightsAI: "Truth prepares better than comfort",
      entryLengthWords: 58,
      daysSinceEntry: 9,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["death", "honesty", "teaching"],
      createdTime: "2026-01-03T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-18",
      name: "The Modi and Magni Fight",
      type: "Work",
      date: "2026-01-03",
      timestamp: "2026-01-03T12:00:00Z",
      text: "Thor's sons found us. Modi and Magni. They fought as one, like we were prey. But I have killed gods before. When Magni fell, I saw fear in Modi's eyes. Good. Let the Aesir know - Kratos protects what is his.",
      userId: "demo-kratos",
      inferredMode: "Fierce",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Power vs. Vulnerability",
      snapshot: "God-slaying",
      loops: "",
      nextAction: "Prepare for retaliation",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Killed Thor's son Magni in battle",
      actionableInsightsAI: "Victory brings new enemies",
      entryLengthWords: 52,
      daysSinceEntry: 9,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["combat", "gods", "protection"],
      createdTime: "2026-01-03T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-19",
      name: "Atreus's Arrogance",
      type: "Family",
      date: "2026-01-02",
      timestamp: "2026-01-02T18:00:00Z",
      text: "The boy learned he is part god today. Since then, he has become... different. Cruel. Mocking enemies before killing them. This is not what I wanted. Power without wisdom destroys. I must reach him before it's too late.",
      userId: "demo-kratos",
      inferredMode: "Alarmed",
      inferredEnergy: "Elevated",
      energyShape: "Chaotic",
      contradiction: "Growth vs. Comfort",
      snapshot: "Son's corruption",
      loops: "Power corrupts pattern",
      nextAction: "Intervene immediately",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Atreus becoming arrogant after god revelation",
      actionableInsightsAI: "Power revelation requires guidance",
      entryLengthWords: 48,
      daysSinceEntry: 10,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["arrogance", "power", "corruption"],
      createdTime: "2026-01-02T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-20",
      name: "I Told Him Everything",
      type: "Emotional",
      date: "2026-01-02",
      timestamp: "2026-01-02T22:00:00Z",
      text: "I told Atreus what I am. What I did in Greece. The gods I killed. My family I... He cried. Not from fear but disappointment. Then he hugged me. Said we can be better. Both of us. This boy. This impossible boy.",
      userId: "demo-kratos",
      inferredMode: "Raw",
      inferredEnergy: "Drained",
      energyShape: "Heavy",
      contradiction: "Closeness vs. Distance",
      snapshot: "Truth revealed",
      loops: "",
      nextAction: "Rebuild trust",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Confessed entire past to Atreus",
      actionableInsightsAI: "Truth enables authentic connection",
      entryLengthWords: 52,
      daysSinceEntry: 10,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["confession", "vulnerability", "acceptance"],
      createdTime: "2026-01-02T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-21",
      name: "Week Three Summary",
      type: "Reflection",
      date: "2026-01-02",
      timestamp: "2026-01-02T06:00:00Z",
      text: "The hardest week yet. Not the battles - those I understand. But the conversations. The truths I could no longer hide. Atreus knows now. Everything. And still he calls me Father. I am not worthy. But I will try to be.",
      userId: "demo-kratos",
      inferredMode: "Humbled",
      inferredEnergy: "Balanced",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Week reflection",
      loops: "",
      nextAction: "Earn his trust",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Week of difficult truths and breakthroughs",
      actionableInsightsAI: "Worthiness is earned through action",
      entryLengthWords: 50,
      daysSinceEntry: 11,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["growth", "truth", "redemption"],
      createdTime: "2026-01-02T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 4 - Freya, Complex Emotions
    {
      id: "kratos-22",
      name: "Freya's True Identity",
      type: "Cognitive",
      date: "2026-01-01",
      timestamp: "2026-01-01T12:00:00Z",
      text: "The witch. Freya. Queen of the Valkyries. Odin's ex-wife. Baldur's mother. The layers of deception in this realm run deep. Yet she helped us. Healed my son. Perhaps even gods can act beyond their nature.",
      userId: "demo-kratos",
      inferredMode: "Contemplative",
      inferredEnergy: "Moderate",
      energyShape: "Uneven",
      contradiction: "Logic vs. Faith",
      snapshot: "Identity revelation",
      loops: "",
      nextAction: "Reassess alliances",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Processing Freya's true divine identity",
      actionableInsightsAI: "People contain multitudes",
      entryLengthWords: 46,
      daysSinceEntry: 12,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["deception", "gods", "complexity"],
      createdTime: "2026-01-01T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-23",
      name: "I Understand Freya Now",
      type: "Reflection",
      date: "2026-01-01",
      timestamp: "2026-01-01T18:00:00Z",
      text: "She made Baldur invulnerable to protect him. He hated her for it. I have done terrible things to protect Atreus too. We are more alike than I admitted. Parents who love too fiercely. Who damage what we try to save.",
      userId: "demo-kratos",
      inferredMode: "Understanding",
      inferredEnergy: "Low",
      energyShape: "Flowing",
      contradiction: "Closeness vs. Distance",
      snapshot: "Parental empathy",
      loops: "",
      nextAction: "Learn from her mistakes",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Finding common ground with Freya",
      actionableInsightsAI: "Overprotection can harm as much as neglect",
      entryLengthWords: 48,
      daysSinceEntry: 12,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["empathy", "parenting", "mistakes"],
      createdTime: "2026-01-01T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-24",
      name: "Missing Faye",
      type: "Emotional",
      date: "2026-01-01",
      timestamp: "2026-01-01T22:00:00Z",
      text: "Watched Atreus sleep tonight. He has her eyes. Her stubborn jaw. I miss her with a depth I cannot name. She would know what to say to him. How to guide without controlling. I am learning. Slowly. For her. For him.",
      userId: "demo-kratos",
      inferredMode: "Grieving",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Joy vs. Sadness",
      snapshot: "Late night grief",
      loops: "Missing partner",
      nextAction: "Honor her memory through actions",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Deep grief for Faye while watching son",
      actionableInsightsAI: "Grief and love coexist",
      entryLengthWords: 50,
      daysSinceEntry: 13,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["grief", "love", "memory"],
      createdTime: "2026-01-01T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-25",
      name: "Helheim's Cold",
      type: "Health",
      date: "2025-12-31",
      timestamp: "2025-12-31T06:00:00Z",
      text: "The realm of the dead. Helheim. Cold beyond cold. Even I felt it in my bones. We came for an artifact and found the truth of Baldur's curse. Nothing can kill him. Nothing except... mistletoe. The smallest thing.",
      userId: "demo-kratos",
      inferredMode: "Calculating",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Logic vs. Faith",
      snapshot: "Helheim journey",
      loops: "",
      nextAction: "Use knowledge wisely",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Discovered Baldur's weakness in Helheim",
      actionableInsightsAI: "Small details can be decisive",
      entryLengthWords: 48,
      daysSinceEntry: 13,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["death", "discovery", "weakness"],
      createdTime: "2025-12-31T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-26",
      name: "Atreus Showed Mercy",
      type: "Family",
      date: "2025-12-31",
      timestamp: "2025-12-31T12:00:00Z",
      text: "Modi attacked us again, broken and desperate. I would have killed him without thought. But Atreus said no. Showed mercy. Let him flee. Part of me raged. Part of me... was proud. The boy is not me. Good.",
      userId: "demo-kratos",
      inferredMode: "Conflicted",
      inferredEnergy: "Moderate",
      energyShape: "Uneven",
      contradiction: "Justice vs. Mercy",
      snapshot: "Mercy moment",
      loops: "",
      nextAction: "Reflect on his choice",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Atreus chose mercy over vengeance",
      actionableInsightsAI: "Children can teach different values",
      entryLengthWords: 50,
      daysSinceEntry: 14,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["mercy", "growth", "pride"],
      createdTime: "2025-12-31T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-27",
      name: "The Mountain Grows Near",
      type: "Work",
      date: "2025-12-31",
      timestamp: "2025-12-31T18:00:00Z",
      text: "We can see it now. The highest peak. Jotunheim's gateway. Faye's final destination. Every step closer is a step toward goodbye. When we scatter her ashes, what then? A future I cannot yet imagine.",
      userId: "demo-kratos",
      inferredMode: "Apprehensive",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Past vs. Present",
      snapshot: "Approaching goal",
      loops: "Fear of ending",
      nextAction: "Face the destination",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Nearing journey's end with mixed feelings",
      actionableInsightsAI: "Endings make space for beginnings",
      entryLengthWords: 48,
      daysSinceEntry: 14,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["destination", "closure", "future"],
      createdTime: "2025-12-31T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-28",
      name: "Week Four Summary",
      type: "Reflection",
      date: "2025-12-30",
      timestamp: "2025-12-30T22:00:00Z",
      text: "Week four. We have crossed death's realm and returned. Atreus showed mercy I could not have given. The mountain awaits. I feel the end approaching - not of life, but of this journey. And the beginning of another.",
      userId: "demo-kratos",
      inferredMode: "Reflective",
      inferredEnergy: "Balanced",
      energyShape: "Centered",
      contradiction: "Past vs. Present",
      snapshot: "Weekly summary",
      loops: "",
      nextAction: "Complete the mission",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Fourth week marked by transformation",
      actionableInsightsAI: "Every ending contains new beginnings",
      entryLengthWords: 48,
      daysSinceEntry: 15,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["reflection", "transformation", "endings"],
      createdTime: "2025-12-30T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 5 - Baldur Fight, Father-Son Bonding
    {
      id: "kratos-29",
      name: "Baldur's Return",
      type: "Work",
      date: "2025-12-30",
      timestamp: "2025-12-30T06:00:00Z",
      text: "He found us again. Baldur. The stranger from our door. But this time I know his weakness. The mistletoe arrow on Atreus's quiver. An accident of fate. Or perhaps Faye knew. She always knew.",
      userId: "demo-kratos",
      inferredMode: "Prepared",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Action vs. Fear",
      snapshot: "Final confrontation",
      loops: "",
      nextAction: "End this",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Prepared for final fight with Baldur",
      actionableInsightsAI: "Preparation meets opportunity",
      entryLengthWords: 44,
      daysSinceEntry: 16,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["combat", "fate", "preparation"],
      createdTime: "2025-12-30T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-30",
      name: "I Killed Baldur",
      type: "Work",
      date: "2025-12-30",
      timestamp: "2025-12-30T12:00:00Z",
      text: "He would not stop. Even broken, bleeding, mortal - he tried to kill Freya. His own mother. I snapped his neck. Freya screamed. Cursed me. Swore vengeance. I understand. I would do the same.",
      userId: "demo-kratos",
      inferredMode: "Grim",
      inferredEnergy: "Drained",
      energyShape: "Heavy",
      contradiction: "Justice vs. Mercy",
      snapshot: "God-kill aftermath",
      loops: "New enemies created",
      nextAction: "Accept the consequences",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Killed Baldur, earned Freya's hatred",
      actionableInsightsAI: "Right actions can still have costs",
      entryLengthWords: 46,
      daysSinceEntry: 16,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["death", "consequence", "vengeance"],
      createdTime: "2025-12-30T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-31",
      name: "We Reached Jotunheim",
      type: "Emotional",
      date: "2025-12-29",
      timestamp: "2025-12-29T18:00:00Z",
      text: "The realm of the giants. Empty. Silent. They are all gone. But the murals... they show our journey. Faye's journey. She knew everything. Every fight. Every choice. She was a giant. Atreus is half giant, half god.",
      userId: "demo-kratos",
      inferredMode: "Stunned",
      inferredEnergy: "Low",
      energyShape: "Chaotic",
      contradiction: "Logic vs. Faith",
      snapshot: "Truth revealed",
      loops: "",
      nextAction: "Process this truth",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Discovered Faye was a giant all along",
      actionableInsightsAI: "Sometimes we know less than we think",
      entryLengthWords: 50,
      daysSinceEntry: 17,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["revelation", "identity", "fate"],
      createdTime: "2025-12-29T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-32",
      name: "Scattering the Ashes",
      type: "Emotional",
      date: "2025-12-29",
      timestamp: "2025-12-29T22:00:00Z",
      text: "We did it. The highest peak. Her ashes joined the wind. Atreus cried. I... I let myself feel it. The loss. The love. The gratitude for the years she gave me. 'I'm ready,' Atreus said. So am I, boy. So am I.",
      userId: "demo-kratos",
      inferredMode: "Peaceful",
      inferredEnergy: "Low",
      energyShape: "Flowing",
      contradiction: "Joy vs. Sadness",
      snapshot: "Mission complete",
      loops: "",
      nextAction: "Begin new chapter",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Completed Faye's final wish together",
      actionableInsightsAI: "Closure enables new beginnings",
      entryLengthWords: 52,
      daysSinceEntry: 17,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["closure", "grief", "peace"],
      createdTime: "2025-12-29T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-33",
      name: "Atreus's True Name",
      type: "Family",
      date: "2025-12-29",
      timestamp: "2025-12-29T06:00:00Z",
      text: "The murals called him Loki. Faye's name for him among her people. The trickster god. The giants saw a different future. But prophecy is not fate. He will be who he chooses to be. I will make sure of that.",
      userId: "demo-kratos",
      inferredMode: "Protective",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Past vs. Present",
      snapshot: "Identity revelation",
      loops: "",
      nextAction: "Guide his choices",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Learned Atreus's prophetic name is Loki",
      actionableInsightsAI: "Prophecy need not dictate destiny",
      entryLengthWords: 50,
      daysSinceEntry: 18,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["prophecy", "identity", "choice"],
      createdTime: "2025-12-29T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-34",
      name: "Back Home",
      type: "Health",
      date: "2025-12-28",
      timestamp: "2025-12-28T12:00:00Z",
      text: "Returned to Midgard. The witch's house is shelter for now. Freya's wrath awaits. Odin will come. But tonight, we rest. Atreus is already asleep. I watch him breathe. Alive. Safe. For now, that is enough.",
      userId: "demo-kratos",
      inferredMode: "Vigilant",
      inferredEnergy: "Low",
      energyShape: "Centered",
      contradiction: "Action vs. Rest",
      snapshot: "Quiet moment",
      loops: "",
      nextAction: "Rest while possible",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Brief peace after completing mission",
      actionableInsightsAI: "Rest between storms is essential",
      entryLengthWords: 46,
      daysSinceEntry: 18,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["rest", "safety", "vigilance"],
      createdTime: "2025-12-28T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-35",
      name: "Week Five Summary",
      type: "Reflection",
      date: "2025-12-28",
      timestamp: "2025-12-28T18:00:00Z",
      text: "Week five. We killed a god. Learned the truth about Faye. Scattered her ashes at the peak of creation. And returned alive. Father and son. I came to Midgard to escape my past. Instead, I found a future.",
      userId: "demo-kratos",
      inferredMode: "Hopeful",
      inferredEnergy: "Balanced",
      energyShape: "Rising",
      contradiction: "Past vs. Present",
      snapshot: "Weekly reflection",
      loops: "",
      nextAction: "Face what comes",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Transformative week completing main journey",
      actionableInsightsAI: "Running from past led to future",
      entryLengthWords: 48,
      daysSinceEntry: 19,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["completion", "hope", "future"],
      createdTime: "2025-12-28T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 6 - New Beginnings, Hope for Atreus
    {
      id: "kratos-36",
      name: "Training Together",
      type: "Family",
      date: "2025-12-28",
      timestamp: "2025-12-28T22:00:00Z",
      text: "Morning training with Atreus. Different now. I still correct him but I also praise. He still frustrates me but I breathe first. We are both learning. The axe and the bow. Father and son. Together.",
      userId: "demo-kratos",
      inferredMode: "Connected",
      inferredEnergy: "Moderate",
      energyShape: "Flowing",
      contradiction: "Growth vs. Comfort",
      snapshot: "Training evolved",
      loops: "",
      nextAction: "Continue daily training",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Training relationship has transformed",
      actionableInsightsAI: "Growth in relationship requires ongoing effort",
      entryLengthWords: 46,
      daysSinceEntry: 20,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["training", "growth", "connection"],
      createdTime: "2025-12-28T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-37",
      name: "Mimir Tells of Ragnarok",
      type: "Cognitive",
      date: "2025-12-27",
      timestamp: "2025-12-27T06:00:00Z",
      text: "Mimir spoke of Fimbulwinter. Three years of endless cold before Ragnarok - the end of all things. The snow has started. We may have triggered it. But ends can also be beginnings. I have died before.",
      userId: "demo-kratos",
      inferredMode: "Accepting",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Past vs. Present",
      snapshot: "Apocalypse prophecy",
      loops: "",
      nextAction: "Prepare for anything",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Learning about coming Ragnarok",
      actionableInsightsAI: "Even apocalypse is just another challenge",
      entryLengthWords: 48,
      daysSinceEntry: 20,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["prophecy", "apocalypse", "acceptance"],
      createdTime: "2025-12-27T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-38",
      name: "Atreus Asked About Greece",
      type: "Family",
      date: "2025-12-27",
      timestamp: "2025-12-27T12:00:00Z",
      text: "The boy asked to hear about Greece. Not the kills - the life before. Sparta. My brother. The training. The honor. I told him stories I had buried. He listened without judgment. Faye would be proud of him.",
      userId: "demo-kratos",
      inferredMode: "Nostalgic",
      inferredEnergy: "Moderate",
      energyShape: "Flowing",
      contradiction: "Past vs. Present",
      snapshot: "Sharing history",
      loops: "",
      nextAction: "Share more when ready",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Shared Spartan history with Atreus",
      actionableInsightsAI: "Past has good memories too",
      entryLengthWords: 50,
      daysSinceEntry: 21,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["history", "sharing", "connection"],
      createdTime: "2025-12-27T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-39",
      name: "I Laughed Today",
      type: "Emotional",
      date: "2025-12-27",
      timestamp: "2025-12-27T18:00:00Z",
      text: "Atreus made a joke about the head talking too much. Mimir pretended offense. Before I knew it, I laughed. A real laugh. When did I last laugh? I cannot remember. The boy looked at me like I had sprouted wings.",
      userId: "demo-kratos",
      inferredMode: "Surprised",
      inferredEnergy: "Elevated",
      energyShape: "Expanding",
      contradiction: "Joy vs. Sadness",
      snapshot: "Unexpected joy",
      loops: "",
      nextAction: "Allow more joy",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Experienced genuine laughter for first time",
      actionableInsightsAI: "Joy can return unexpectedly",
      entryLengthWords: 50,
      daysSinceEntry: 21,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["joy", "laughter", "healing"],
      createdTime: "2025-12-27T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-40",
      name: "Building a New Home",
      type: "Work",
      date: "2025-12-26",
      timestamp: "2025-12-26T22:00:00Z",
      text: "Started constructing a proper cabin. Atreus helps with the lighter wood. We work in comfortable silence. Building something instead of destroying. My hands know war but they can also know creation.",
      userId: "demo-kratos",
      inferredMode: "Purposeful",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Growth vs. Comfort",
      snapshot: "Construction project",
      loops: "",
      nextAction: "Complete the cabin",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Building new home together with son",
      actionableInsightsAI: "Creation heals as much as destruction wounds",
      entryLengthWords: 42,
      daysSinceEntry: 22,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["creation", "building", "healing"],
      createdTime: "2025-12-26T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-41",
      name: "Thor Will Come",
      type: "Cognitive",
      date: "2025-12-26",
      timestamp: "2025-12-26T06:00:00Z",
      text: "We killed his sons. We broke his father's spells. Thor will come for vengeance. I should feel dread. Instead I feel... ready. I am no longer running. I stand. With my son. Let the God of Thunder come.",
      userId: "demo-kratos",
      inferredMode: "Resolute",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Action vs. Fear",
      snapshot: "Accepting challenge",
      loops: "",
      nextAction: "Train and prepare",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Ready to face Thor's inevitable vengeance",
      actionableInsightsAI: "Standing ground beats running",
      entryLengthWords: 48,
      daysSinceEntry: 22,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["readiness", "standing ground", "courage"],
      createdTime: "2025-12-26T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-42",
      name: "Teaching Him My Language",
      type: "Family",
      date: "2025-12-26",
      timestamp: "2025-12-26T12:00:00Z",
      text: "Taught Atreus Greek today. Simple words at first. Father. Son. Strength. Honor. He repeated them badly but with determination. Faye taught him the old tongue. Now I teach him mine. He carries both of us.",
      userId: "demo-kratos",
      inferredMode: "Tender",
      inferredEnergy: "Moderate",
      energyShape: "Flowing",
      contradiction: "Past vs. Present",
      snapshot: "Teaching moment",
      loops: "",
      nextAction: "Continue language lessons",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Teaching Atreus Greek language",
      actionableInsightsAI: "Passing on heritage connects generations",
      entryLengthWords: 46,
      daysSinceEntry: 23,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["language", "heritage", "teaching"],
      createdTime: "2025-12-26T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "kratos-43",
      name: "Week Six Summary",
      type: "Reflection",
      date: "2025-12-25",
      timestamp: "2025-12-25T18:00:00Z",
      text: "Six weeks since we began. I came here as a ghost trying to be human. I am still learning. But I am no longer alone in the dark. Atreus lights the way. And perhaps, together, we can face whatever comes next.",
      userId: "demo-kratos",
      inferredMode: "Hopeful",
      inferredEnergy: "Balanced",
      energyShape: "Rising",
      contradiction: "Growth vs. Comfort",
      snapshot: "Journey reflection",
      loops: "",
      nextAction: "Continue forward together",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Six-week transformation from isolation to connection",
      actionableInsightsAI: "Growth happens in relationship",
      entryLengthWords: 50,
      daysSinceEntry: 23,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["growth", "hope", "connection"],
      createdTime: "2025-12-25T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-44",
      name: "The Boy Becomes a Man",
      type: "Family",
      date: "2025-12-25",
      timestamp: "2025-12-25T22:00:00Z",
      text: "Atreus stood between me and danger today. Shielded me with his own body. I should have scolded him. Instead I held him. Brief. Awkward. But real. He is not the boy who missed every arrow. He is becoming something more.",
      userId: "demo-kratos",
      inferredMode: "Proud",
      inferredEnergy: "Elevated",
      energyShape: "Expanding",
      contradiction: "Closeness vs. Distance",
      snapshot: "Pride moment",
      loops: "",
      nextAction: "Trust him more",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Witnessed Atreus's growth into protector",
      actionableInsightsAI: "Children grow when we let them",
      entryLengthWords: 50,
      daysSinceEntry: 24,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["growth", "pride", "protection"],
      createdTime: "2025-12-25T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "kratos-45",
      name: "Looking Forward",
      type: "Reflection",
      date: "2025-12-25",
      timestamp: "2025-12-25T06:00:00Z",
      text: "The past cannot be changed. The future cannot be certain. But today - today I have my son. Today we build. Today we prepare. Today we are alive. For a ghost like me, that is more than I ever expected. It is enough.",
      userId: "demo-kratos",
      inferredMode: "Content",
      inferredEnergy: "Balanced",
      energyShape: "Centered",
      contradiction: "Past vs. Present",
      snapshot: "Acceptance moment",
      loops: "",
      nextAction: "Live each day",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Finding peace in present moment",
      actionableInsightsAI: "Today is enough",
      entryLengthWords: 50,
      daysSinceEntry: 43,
      isRecent: false,
      sentimentAI: "Positive",
      themeTagsAI: ["acceptance", "presence", "peace"],
      createdTime: "2025-12-25T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
  ]
}
