// Nova Demo Data - Startup Founder themed entries
// Note: Returns base demo entries without decomposition fields (added by withDefaults in demoPersonas.ts)

export function getNovaDemoData() {
  return [
    // Week 1 - Pitch Deck Stress, Investor Meetings
    {
      id: "nova-1",
      name: "Another VC Said No",
      type: "Work",
      date: "2026-01-08",
      timestamp: "2026-01-08T06:00:00Z",
      text: "Third rejection this week. 'Love the team, not the market.' 'Great traction, wrong timing.' The reasons blur together. 12 months of runway left. Need to close this round or we're done. Deep breath. Update the deck. Try again tomorrow.",
      userId: "demo-nova",
      inferredMode: "Determined",
      inferredEnergy: "Drained",
      energyShape: "Heavy",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Rejection aftermath",
      loops: "Rejection processing",
      nextAction: "Refine pitch for tomorrow",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Processing third investor rejection this week",
      actionableInsightsAI: "Rejection is data for improvement",
      entryLengthWords: 52,
      daysSinceEntry: 0,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["fundraising", "rejection", "persistence"],
      createdTime: "2026-01-08T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-2",
      name: "Midnight Pitch Revision",
      type: "Creativity",
      date: "2026-01-08",
      timestamp: "2026-01-08T12:00:00Z",
      text: "Rewrote the entire market size slide at midnight. Coffee number five. The TAM calculation was wrong - we've been underselling ourselves. With the corrected figures, we're a $2B opportunity, not $500M. Why didn't I catch this before?",
      userId: "demo-nova",
      inferredMode: "Energized",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Growth vs. Comfort",
      snapshot: "Late night breakthrough",
      loops: "",
      nextAction: "Test new pitch tomorrow",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Late night discovery of better market positioning",
      actionableInsightsAI: "Fresh eyes find what tired ones miss",
      entryLengthWords: 50,
      daysSinceEntry: 1,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["pitch deck", "breakthrough", "market"],
      createdTime: "2026-01-08T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-3",
      name: "Co-founder Tension",
      type: "Family",
      date: "2026-01-08",
      timestamp: "2026-01-08T18:00:00Z",
      text: "Maya and I argued about the product roadmap again. She wants to build features, I want to close funding first. Both right, both wrong. We used to finish each other's sentences. Now we interrupt each other's ideas. Need to fix this.",
      userId: "demo-nova",
      inferredMode: "Conflicted",
      inferredEnergy: "Moderate",
      energyShape: "Chaotic",
      contradiction: "Closeness vs. Distance",
      snapshot: "Co-founder conflict",
      loops: "Strategy disagreements",
      nextAction: "Schedule alignment talk",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Ongoing tension with co-founder about priorities",
      actionableInsightsAI: "Alignment conversations before they're urgent",
      entryLengthWords: 52,
      daysSinceEntry: 1,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["co-founder", "conflict", "alignment"],
      createdTime: "2026-01-08T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-4",
      name: "User Interview Gold",
      type: "Work",
      date: "2026-01-07",
      timestamp: "2026-01-07T22:00:00Z",
      text: "Best user interview yet! Sarah from TechCorp said our product 'saved her team 15 hours a week.' Direct quote for the deck. When users tell you the value, believe them. We're not building features, we're buying back people's time.",
      userId: "demo-nova",
      inferredMode: "Validated",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Customer validation",
      loops: "",
      nextAction: "Get more testimonials",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Powerful customer testimonial validates product",
      actionableInsightsAI: "Users articulate value better than founders",
      entryLengthWords: 50,
      daysSinceEntry: 2,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["customers", "validation", "value"],
      createdTime: "2026-01-07T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-5",
      name: "The 3 AM Panic",
      type: "Health",
      date: "2026-01-07",
      timestamp: "2026-01-07T06:00:00Z",
      text: "Woke up heart pounding. Dreamt the company failed. Everyone blamed me. The investors, the team, my parents. Took an hour to calm down. This is unsustainable. Need to talk to someone. Maybe that therapist my mentor mentioned.",
      userId: "demo-nova",
      inferredMode: "Anxious",
      inferredEnergy: "Low",
      energyShape: "Chaotic",
      contradiction: "Action vs. Fear",
      snapshot: "Anxiety attack",
      loops: "Founder anxiety",
      nextAction: "Book therapist appointment",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Panic attack reveals need for mental health support",
      actionableInsightsAI: "Founder wellbeing is business critical",
      entryLengthWords: 52,
      daysSinceEntry: 2,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["anxiety", "mental health", "burnout"],
      createdTime: "2026-01-07T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-6",
      name: "The Good Investor",
      type: "Work",
      date: "2026-01-07",
      timestamp: "2026-01-07T12:00:00Z",
      text: "Met Sarah Chen from Horizon Ventures. Different vibe. She asked about our team's mental health, our runway anxiety, how we handle disagreements. Then the product. If she passes, at least I know good investors exist.",
      userId: "demo-nova",
      inferredMode: "Hopeful",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Quality investor meeting",
      loops: "",
      nextAction: "Follow up thoughtfully",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Positive meeting with values-aligned investor",
      actionableInsightsAI: "Find investors who care about founders",
      entryLengthWords: 48,
      daysSinceEntry: 3,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["investors", "values", "hope"],
      createdTime: "2026-01-07T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-7",
      name: "Team Standup Reality",
      type: "Work",
      date: "2026-01-06",
      timestamp: "2026-01-06T18:00:00Z",
      text: "Monday standup. Dev team is crushing it. Marketing needs direction. I need to be present, not just physically but mentally. They can see when I'm distracted by funding. As founder, my anxiety is contagious. Must do better.",
      userId: "demo-nova",
      inferredMode: "Aware",
      inferredEnergy: "Moderate",
      energyShape: "Uneven",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Leadership reflection",
      loops: "Distracted leadership",
      nextAction: "Compartmentalize better",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Recognized impact of founder stress on team",
      actionableInsightsAI: "Leader's energy affects everyone",
      entryLengthWords: 50,
      daysSinceEntry: 3,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["leadership", "team", "presence"],
      createdTime: "2026-01-06T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 2 - Product Pivots, User Feedback
    {
      id: "nova-8",
      name: "The Pivot Conversation",
      type: "Cognitive",
      date: "2026-01-06",
      timestamp: "2026-01-06T22:00:00Z",
      text: "Data is clear: enterprise loves us, SMB doesn't convert. Maya wants to stay broad, I say focus on enterprise. This might be a pivot. Pivots feel like failure but data says it's wisdom. Need to get on the same page.",
      userId: "demo-nova",
      inferredMode: "Analytical",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Growth vs. Comfort",
      snapshot: "Strategic decision",
      loops: "",
      nextAction: "Present data to Maya",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Data pointing toward enterprise focus pivot",
      actionableInsightsAI: "Pivots based on data aren't failure",
      entryLengthWords: 48,
      daysSinceEntry: 4,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["pivot", "strategy", "data"],
      createdTime: "2026-01-06T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-9",
      name: "First Enterprise Deal!",
      type: "Work",
      date: "2026-01-06",
      timestamp: "2026-01-06T06:00:00Z",
      text: "SIGNED! TechCorp just signed an annual contract. $48K ARR. Our first real enterprise deal. Maya and I screamed on the call after they hung up. Then we cried. Then we ordered pizza. This is why we do this. This.",
      userId: "demo-nova",
      inferredMode: "Ecstatic",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Joy vs. Sadness",
      snapshot: "Major win",
      loops: "",
      nextAction: "Replicate this sale",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Closed first major enterprise customer",
      actionableInsightsAI: "Celebrate wins before moving on",
      entryLengthWords: 50,
      daysSinceEntry: 4,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["sales", "milestone", "celebration"],
      createdTime: "2026-01-06T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-10",
      name: "The Feature Graveyard",
      type: "Reflection",
      date: "2026-01-05",
      timestamp: "2026-01-05T12:00:00Z",
      text: "Made a list of features we built that nobody uses. Three months of work. Painful to see. But also clarifying. We were building what we thought they wanted, not what they actually needed. Expensive lesson. Won't forget it.",
      userId: "demo-nova",
      inferredMode: "Regretful",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Growth vs. Comfort",
      snapshot: "Learning from mistakes",
      loops: "Over-building pattern",
      nextAction: "Talk to users before building",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Cataloging wasted development effort",
      actionableInsightsAI: "Build-measure-learn, in that order",
      entryLengthWords: 50,
      daysSinceEntry: 5,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["product", "mistakes", "learning"],
      createdTime: "2026-01-05T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-11",
      name: "Mentor Check-in",
      type: "Family",
      date: "2026-01-05",
      timestamp: "2026-01-05T18:00:00Z",
      text: "Call with David, my YC mentor. He said the hard part isn't finding product-market fit - it's keeping yourself together while searching. Asked about sleep, exercise, relationships. Felt like therapy. Maybe that's what good mentorship is.",
      userId: "demo-nova",
      inferredMode: "Supported",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Mentorship moment",
      loops: "",
      nextAction: "Implement his advice",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Mentor focused on founder wellbeing",
      actionableInsightsAI: "Good mentors care about the person",
      entryLengthWords: 50,
      daysSinceEntry: 5,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["mentorship", "support", "wellbeing"],
      createdTime: "2026-01-05T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-12",
      name: "Runway Calculator Reality",
      type: "Cognitive",
      date: "2026-01-05",
      timestamp: "2026-01-05T22:00:00Z",
      text: "Updated the runway spreadsheet. 11 months now, not 12. Burn rate is creeping up. Need to either raise soon or cut costs. Both options have consequences. The math doesn't care about my feelings. It just... counts down.",
      userId: "demo-nova",
      inferredMode: "Stressed",
      inferredEnergy: "Moderate",
      energyShape: "Heavy",
      contradiction: "Logic vs. Faith",
      snapshot: "Financial pressure",
      loops: "Runway anxiety",
      nextAction: "Model scenarios",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Runway shorter than expected",
      actionableInsightsAI: "Update financial projections regularly",
      entryLengthWords: 50,
      daysSinceEntry: 6,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["runway", "finance", "pressure"],
      createdTime: "2026-01-05T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-13",
      name: "Coffee with Old Colleague",
      type: "Leisure",
      date: "2026-01-04",
      timestamp: "2026-01-04T06:00:00Z",
      text: "Had coffee with James from my old job. He's still there, comfortable, bored. I'm terrified, exhausted, alive. Wouldn't trade it. He asked if I miss the stability. I said no. I think I meant it. Mostly.",
      userId: "demo-nova",
      inferredMode: "Reflective",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Life comparison",
      loops: "",
      nextAction: "Remember this feeling",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Compared startup life to corporate path",
      actionableInsightsAI: "Growth often feels worse than stagnation",
      entryLengthWords: 50,
      daysSinceEntry: 6,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["reflection", "choices", "growth"],
      createdTime: "2026-01-04T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-14",
      name: "Week One Summary",
      type: "Reflection",
      date: "2026-01-04",
      timestamp: "2026-01-04T12:00:00Z",
      text: "Week one of this new year. Three rejections, one major customer, one panic attack, one breakthrough. The founder rollercoaster continues. At least the highs were as high as the lows were low. That's... something.",
      userId: "demo-nova",
      inferredMode: "Balanced",
      inferredEnergy: "Moderate",
      energyShape: "Uneven",
      contradiction: "Joy vs. Sadness",
      snapshot: "Weekly reflection",
      loops: "",
      nextAction: "Keep going",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "First week showed extreme founder highs and lows",
      actionableInsightsAI: "Embrace the rollercoaster",
      entryLengthWords: 46,
      daysSinceEntry: 7,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["reflection", "balance", "resilience"],
      createdTime: "2026-01-04T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 3 - Co-founder Tension, Hiring
    {
      id: "nova-15",
      name: "The Hard Conversation",
      type: "Family",
      date: "2026-01-04",
      timestamp: "2026-01-04T18:00:00Z",
      text: "Finally had the alignment talk with Maya. Three hours. Some tears. We agreed: enterprise focus, hire two more engineers, revisit roles. We're still co-founders. Still friends. But now with clearer boundaries. Growth hurts.",
      userId: "demo-nova",
      inferredMode: "Relieved",
      inferredEnergy: "Drained",
      energyShape: "Heavy",
      contradiction: "Closeness vs. Distance",
      snapshot: "Co-founder alignment",
      loops: "",
      nextAction: "Implement agreements",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Difficult but necessary co-founder conversation",
      actionableInsightsAI: "Hard conversations strengthen partnerships",
      entryLengthWords: 50,
      daysSinceEntry: 8,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["co-founder", "alignment", "growth"],
      createdTime: "2026-01-04T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-16",
      name: "New Year Fundraising Goal",
      type: "Work",
      date: "2026-01-03",
      timestamp: "2026-01-03T22:00:00Z",
      text: "New Year's resolution: Close the seed round by March. $1.5M at $8M cap. Specific goals feel scarier than vague hopes. But specific goals get measured. And measured goals get achieved. Here's to terrifying specificity.",
      userId: "demo-nova",
      inferredMode: "Determined",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Action vs. Fear",
      snapshot: "Goal setting",
      loops: "",
      nextAction: "Break into weekly targets",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Set specific fundraising goal for new year",
      actionableInsightsAI: "Specific goals enable accountability",
      entryLengthWords: 48,
      daysSinceEntry: 8,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["goals", "fundraising", "commitment"],
      createdTime: "2026-01-03T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-17",
      name: "Hiring Pain",
      type: "Work",
      date: "2026-01-03",
      timestamp: "2026-01-03T06:00:00Z",
      text: "Interviewed seven engineers this week. All either too expensive or not quite right. The ones we can afford need training. The ones who are ready want FAANG salaries. How do early startups build great teams? Still figuring it out.",
      userId: "demo-nova",
      inferredMode: "Frustrated",
      inferredEnergy: "Moderate",
      energyShape: "Heavy",
      contradiction: "Growth vs. Comfort",
      snapshot: "Hiring struggles",
      loops: "Hiring difficulties",
      nextAction: "Expand search methods",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Struggling to find affordable quality hires",
      actionableInsightsAI: "Early-stage hiring requires creativity",
      entryLengthWords: 50,
      daysSinceEntry: 9,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["hiring", "challenges", "team"],
      createdTime: "2026-01-03T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-18",
      name: "The Underdog Hire",
      type: "Work",
      date: "2026-01-03",
      timestamp: "2026-01-03T12:00:00Z",
      text: "Made an offer to Raj - bootcamp grad, zero big company experience, but his eyes light up talking about our product. He accepted immediately. Maya thinks I'm taking a risk. Maybe. But fire in the belly beats polish on the resume.",
      userId: "demo-nova",
      inferredMode: "Confident",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Logic vs. Faith",
      snapshot: "Unconventional hire",
      loops: "",
      nextAction: "Onboard Raj well",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Hired passionate bootcamp grad over experienced candidates",
      actionableInsightsAI: "Passion can outperform credentials",
      entryLengthWords: 52,
      daysSinceEntry: 9,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["hiring", "risk", "potential"],
      createdTime: "2026-01-03T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-19",
      name: "Parent's Concern",
      type: "Family",
      date: "2026-01-02",
      timestamp: "2026-01-02T18:00:00Z",
      text: "Mom called. Asked when I'm getting a 'real job.' Explained startup life for the hundredth time. She doesn't understand but she supports me. That's enough. Dad said nothing - which for him means he's worried. I know, Dad. Me too.",
      userId: "demo-nova",
      inferredMode: "Conflicted",
      inferredEnergy: "Low",
      energyShape: "Uneven",
      contradiction: "Closeness vs. Distance",
      snapshot: "Family pressure",
      loops: "Parental concern",
      nextAction: "Show results eventually",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Navigating parental concern about career choice",
      actionableInsightsAI: "Family support doesn't require understanding",
      entryLengthWords: 52,
      daysSinceEntry: 10,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["family", "support", "pressure"],
      createdTime: "2026-01-02T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-20",
      name: "Competitor Launch",
      type: "Cognitive",
      date: "2026-01-02",
      timestamp: "2026-01-02T22:00:00Z",
      text: "BigTech just launched something similar. Immediate panic. Then I looked closer: bloated, expensive, requires their ecosystem. We're still nimble, focused, affordable. Competition validates the market. Deep breath. Execute faster.",
      userId: "demo-nova",
      inferredMode: "Alert",
      inferredEnergy: "High",
      energyShape: "Chaotic",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Competitive threat",
      loops: "Competitor anxiety",
      nextAction: "Double down on differentiation",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Competitor launch triggered then motivated",
      actionableInsightsAI: "Competition confirms market demand",
      entryLengthWords: 48,
      daysSinceEntry: 10,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["competition", "strategy", "differentiation"],
      createdTime: "2026-01-02T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-21",
      name: "Week Two Summary",
      type: "Reflection",
      date: "2026-01-02",
      timestamp: "2026-01-02T06:00:00Z",
      text: "Week two. Co-founder aligned, engineer hired, competitor emerged. The startup treadmill keeps accelerating. No time to process before the next thing. At least now we're running in the same direction. That matters.",
      userId: "demo-nova",
      inferredMode: "Tired",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Action vs. Rest",
      snapshot: "Weekly reflection",
      loops: "",
      nextAction: "Maintain momentum",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Second week showed progress despite constant pressure",
      actionableInsightsAI: "Aligned teams weather storms better",
      entryLengthWords: 46,
      daysSinceEntry: 11,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["reflection", "progress", "exhaustion"],
      createdTime: "2026-01-02T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 4 - Small Wins, First Paying Customer
    {
      id: "nova-22",
      name: "Product Hunt Launch Day",
      type: "Work",
      date: "2026-01-01",
      timestamp: "2026-01-01T12:00:00Z",
      text: "Launched on Product Hunt. Refreshed the page 47 times in the first hour. We're in 5th place. Community is voting, commenting, sharing. Real people care about what we built. Whatever happens today, this feeling is worth remembering.",
      userId: "demo-nova",
      inferredMode: "Excited",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Launch day",
      loops: "",
      nextAction: "Engage with comments",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Product Hunt launch gaining traction",
      actionableInsightsAI: "Launches matter for momentum",
      entryLengthWords: 50,
      daysSinceEntry: 12,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["launch", "marketing", "excitement"],
      createdTime: "2026-01-01T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-23",
      name: "#3 Product of the Day",
      type: "Emotional",
      date: "2026-01-01",
      timestamp: "2026-01-01T18:00:00Z",
      text: "We finished #3 on Product Hunt! 500+ upvotes, 80 comments, 200 new signups. Team is exhausted but glowing. Maya hugged me. Raj stayed up all night handling support tickets. We're building something real. People want it.",
      userId: "demo-nova",
      inferredMode: "Proud",
      inferredEnergy: "Elevated",
      energyShape: "Expanding",
      contradiction: "Joy vs. Sadness",
      snapshot: "Launch success",
      loops: "",
      nextAction: "Convert signups",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Successful Product Hunt launch validated product",
      actionableInsightsAI: "Success energizes teams",
      entryLengthWords: 50,
      daysSinceEntry: 12,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["success", "validation", "team"],
      createdTime: "2026-01-01T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-24",
      name: "Conversion Reality",
      type: "Cognitive",
      date: "2026-01-01",
      timestamp: "2026-01-01T22:00:00Z",
      text: "Of 200 signups, 15 started trials, 3 look serious. That's 1.5% conversion so far. Lower than hoped. But higher than zero. Need to improve onboarding. The funnel is leaky but at least now I can see where the holes are.",
      userId: "demo-nova",
      inferredMode: "Analytical",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Logic vs. Faith",
      snapshot: "Metrics analysis",
      loops: "",
      nextAction: "Fix onboarding flow",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Analyzing conversion rates post-launch",
      actionableInsightsAI: "Data reveals improvement opportunities",
      entryLengthWords: 50,
      daysSinceEntry: 13,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["metrics", "conversion", "analysis"],
      createdTime: "2026-01-01T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-25",
      name: "Christmas Guilt",
      type: "Family",
      date: "2025-12-31",
      timestamp: "2025-12-31T06:00:00Z",
      text: "Christmas with family but my mind was on the signup dashboard. Mom noticed I was distracted. Dad asked about 'the business thing.' Tried to be present. Mostly failed. The founder mind never fully turns off. That's a problem.",
      userId: "demo-nova",
      inferredMode: "Guilty",
      inferredEnergy: "Low",
      energyShape: "Uneven",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Work-life guilt",
      loops: "Unable to disconnect",
      nextAction: "Set phone boundaries",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Struggled to be present with family on holiday",
      actionableInsightsAI: "Presence requires practice",
      entryLengthWords: 50,
      daysSinceEntry: 14,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["work-life", "family", "presence"],
      createdTime: "2025-12-31T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-26",
      name: "First Self-Serve Sale",
      type: "Work",
      date: "2025-12-31",
      timestamp: "2025-12-31T12:00:00Z",
      text: "Someone paid us $49/month without ever talking to us. Christmas present from a stranger. Screen capture proves someone from Norway signed up at 3am their time. I don't know them. They don't know me. But they trust our product. Magic.",
      userId: "demo-nova",
      inferredMode: "Amazed",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Logic vs. Faith",
      snapshot: "Product-led growth moment",
      loops: "",
      nextAction: "Enable more self-serve",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "First organic self-serve customer converted",
      actionableInsightsAI: "Product-led growth is magical",
      entryLengthWords: 52,
      daysSinceEntry: 14,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["sales", "product", "growth"],
      createdTime: "2025-12-31T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-27",
      name: "Team Morale Check",
      type: "Family",
      date: "2025-12-31",
      timestamp: "2025-12-31T18:00:00Z",
      text: "Asked everyone how they're doing. Actually waited for real answers. Raj is stressed but learning. Maya is hopeful. The contractors are fine. Team feels it - we're onto something. That shared belief is more valuable than anything.",
      userId: "demo-nova",
      inferredMode: "Connected",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Closeness vs. Distance",
      snapshot: "Team connection",
      loops: "",
      nextAction: "Keep checking in",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Team morale strong despite challenges",
      actionableInsightsAI: "Shared belief sustains through hard times",
      entryLengthWords: 48,
      daysSinceEntry: 15,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["team", "morale", "connection"],
      createdTime: "2025-12-31T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-28",
      name: "Week Three Summary",
      type: "Reflection",
      date: "2025-12-30",
      timestamp: "2025-12-30T22:00:00Z",
      text: "Week three. Product Hunt win, first self-serve customer, team aligned. The metrics are improving. Still not 'there' yet, wherever 'there' is. But moving in the right direction. Momentum matters more than position.",
      userId: "demo-nova",
      inferredMode: "Optimistic",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Growth vs. Comfort",
      snapshot: "Weekly reflection",
      loops: "",
      nextAction: "Maintain momentum",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Third week showed encouraging progress",
      actionableInsightsAI: "Direction matters more than speed",
      entryLengthWords: 46,
      daysSinceEntry: 15,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["progress", "momentum", "optimism"],
      createdTime: "2025-12-30T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 5 - Series A Prep, Due Diligence
    {
      id: "nova-29",
      name: "Sarah Chen Said Yes",
      type: "Work",
      date: "2025-12-30",
      timestamp: "2025-12-30T06:00:00Z",
      text: "Horizon Ventures is leading our seed round. Sarah Chen called personally. $1M at $7M pre-money. Not what we wanted, but fair. More importantly, she believes in us. Strategic value beyond the check. We have a lead investor.",
      userId: "demo-nova",
      inferredMode: "Relieved",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Funding milestone",
      loops: "",
      nextAction: "Close the round",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Secured lead investor for seed round",
      actionableInsightsAI: "Right investors matter more than highest valuation",
      entryLengthWords: 50,
      daysSinceEntry: 16,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["funding", "investors", "milestone"],
      createdTime: "2025-12-30T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-30",
      name: "Due Diligence Stress",
      type: "Cognitive",
      date: "2025-12-30",
      timestamp: "2025-12-30T12:00:00Z",
      text: "Lawyers, accountants, compliance checks. Our messy cap table from the early days is coming back to haunt us. Should have done this cleaner from the start. Lesson for next time. For now, just survive the process.",
      userId: "demo-nova",
      inferredMode: "Overwhelmed",
      inferredEnergy: "Drained",
      energyShape: "Heavy",
      contradiction: "Action vs. Fear",
      snapshot: "Legal pressure",
      loops: "Administrative burden",
      nextAction: "One document at a time",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Struggling through due diligence paperwork",
      actionableInsightsAI: "Clean setup saves pain later",
      entryLengthWords: 48,
      daysSinceEntry: 17,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["legal", "due diligence", "stress"],
      createdTime: "2025-12-30T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-31",
      name: "Telling the Team",
      type: "Family",
      date: "2025-12-29",
      timestamp: "2025-12-29T18:00:00Z",
      text: "Told the team about the funding. Raj asked if this means job security. I said yes, for at least 18 months. Maya teared up. We've been running on fumes and faith. Now we have runway. It feels different. We can actually plan.",
      userId: "demo-nova",
      inferredMode: "Grateful",
      inferredEnergy: "Elevated",
      energyShape: "Expanding",
      contradiction: "Joy vs. Sadness",
      snapshot: "Team celebration",
      loops: "",
      nextAction: "Plan the next phase",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Shared funding news with relieved team",
      actionableInsightsAI: "Shared wins strengthen teams",
      entryLengthWords: 52,
      daysSinceEntry: 17,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["team", "funding", "relief"],
      createdTime: "2025-12-29T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-32",
      name: "The Weight Remains",
      type: "Emotional",
      date: "2025-12-29",
      timestamp: "2025-12-29T22:00:00Z",
      text: "Funding secured, but the anxiety hasn't lifted. If anything, it's heavier. Now I'm responsible for investors' money, not just my own. The stakes just got higher. Success or failure will be louder. Is this what I wanted?",
      userId: "demo-nova",
      inferredMode: "Anxious",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Growth vs. Comfort",
      snapshot: "Post-funding anxiety",
      loops: "Responsibility weight",
      nextAction: "Accept new reality",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Success brought new pressure rather than relief",
      actionableInsightsAI: "Leveling up raises expectations",
      entryLengthWords: 50,
      daysSinceEntry: 18,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["anxiety", "responsibility", "pressure"],
      createdTime: "2025-12-29T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-33",
      name: "Therapist Session #1",
      type: "Health",
      date: "2025-12-29",
      timestamp: "2025-12-29T06:00:00Z",
      text: "First session with Dr. Park. She asked why I'm building this company. I couldn't answer clearly. Not for money. Not for fame. Something about making a dent. She said we'll explore that. I'm skeptical but... hopeful.",
      userId: "demo-nova",
      inferredMode: "Open",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Therapy start",
      loops: "",
      nextAction: "Continue sessions",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Started therapy to explore founder motivations",
      actionableInsightsAI: "Understanding 'why' matters for sustainability",
      entryLengthWords: 50,
      daysSinceEntry: 18,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["therapy", "self-discovery", "growth"],
      createdTime: "2025-12-29T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-34",
      name: "Hiring Plan Approved",
      type: "Work",
      date: "2025-12-28",
      timestamp: "2025-12-28T12:00:00Z",
      text: "Board approved hiring plan: two more engineers, one marketer, one customer success. We're going from 5 to 9 people. The company is becoming real. I'm going from builder to manager. Not sure I'm ready. But here we go.",
      userId: "demo-nova",
      inferredMode: "Apprehensive",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Growth vs. Comfort",
      snapshot: "Growth planning",
      loops: "",
      nextAction: "Start hiring",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Approved to nearly double team size",
      actionableInsightsAI: "Growth requires role evolution",
      entryLengthWords: 50,
      daysSinceEntry: 19,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["hiring", "growth", "leadership"],
      createdTime: "2025-12-28T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-35",
      name: "Week Four Summary",
      type: "Reflection",
      date: "2025-12-28",
      timestamp: "2025-12-28T18:00:00Z",
      text: "Week four. Funding closed, therapy started, team growing. On paper, everything I wanted. In practice, new challenges. The mountain doesn't shrink when you climb higher - you just see more mountains. Keep climbing.",
      userId: "demo-nova",
      inferredMode: "Philosophical",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Weekly reflection",
      loops: "",
      nextAction: "Embrace the climb",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Fourth week brought success with new challenges",
      actionableInsightsAI: "Success reveals new challenges",
      entryLengthWords: 46,
      daysSinceEntry: 19,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["growth", "perspective", "challenges"],
      createdTime: "2025-12-28T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 6 - Growth Reflection, Vision Clarity
    {
      id: "nova-36",
      name: "Company Offsite",
      type: "Family",
      date: "2025-12-28",
      timestamp: "2025-12-28T22:00:00Z",
      text: "Took the team to dinner. Not a work meeting - just connection. Learned Raj plays guitar. Maya did improv in college. We're not just colleagues. We're building something together. These relationships are the company's real asset.",
      userId: "demo-nova",
      inferredMode: "Connected",
      inferredEnergy: "Elevated",
      energyShape: "Expanding",
      contradiction: "Closeness vs. Distance",
      snapshot: "Team bonding",
      loops: "",
      nextAction: "More informal gatherings",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Team dinner revealed personal connections",
      actionableInsightsAI: "Teams are humans first",
      entryLengthWords: 48,
      daysSinceEntry: 20,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["team", "culture", "connection"],
      createdTime: "2025-12-28T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-37",
      name: "The Vision Clarifies",
      type: "Cognitive",
      date: "2025-12-27",
      timestamp: "2025-12-27T06:00:00Z",
      text: "Woke up with the mission clear: 'Give every team back 10 hours a week.' Not features. Not technology. Time. We're selling people their lives back. Every product decision should serve that mission. Feels right. Finally.",
      userId: "demo-nova",
      inferredMode: "Clear",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Logic vs. Faith",
      snapshot: "Vision clarity",
      loops: "",
      nextAction: "Communicate to team",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Mission statement crystallized clearly",
      actionableInsightsAI: "Clear missions guide every decision",
      entryLengthWords: 48,
      daysSinceEntry: 20,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["vision", "mission", "clarity"],
      createdTime: "2025-12-27T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-38",
      name: "Learning to Delegate",
      type: "Work",
      date: "2025-12-27",
      timestamp: "2025-12-27T12:00:00Z",
      text: "Let Maya run the product meeting alone. Hardest thing - watching without commenting. She did great. Different from how I'd do it, but that's okay. If I'm the bottleneck, we can't scale. Must let go to grow.",
      userId: "demo-nova",
      inferredMode: "Restraining",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Delegation practice",
      loops: "",
      nextAction: "Delegate more",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Practiced delegation by stepping back",
      actionableInsightsAI: "Founders must learn to let go",
      entryLengthWords: 48,
      daysSinceEntry: 21,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["delegation", "leadership", "growth"],
      createdTime: "2025-12-27T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-39",
      name: "First Board Meeting",
      type: "Work",
      date: "2025-12-27",
      timestamp: "2025-12-27T18:00:00Z",
      text: "Presented to our first real board. Sarah Chen, two angels, Maya, me. Nervous but prepared. They asked hard questions. I didn't have all answers but said so honestly. Vulnerability in the boardroom. Felt weird. Felt right.",
      userId: "demo-nova",
      inferredMode: "Authentic",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Board meeting",
      loops: "",
      nextAction: "Follow up on action items",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "First board meeting went well with honest approach",
      actionableInsightsAI: "Honest uncertainty beats false confidence",
      entryLengthWords: 50,
      daysSinceEntry: 21,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["board", "governance", "honesty"],
      createdTime: "2025-12-27T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-40",
      name: "Raj's First Feature",
      type: "Family",
      date: "2025-12-26",
      timestamp: "2025-12-26T22:00:00Z",
      text: "Raj shipped his first feature solo. Onboarding improvements. 15% increase in trial activations. The bootcamp kid delivered. I was wrong to doubt. Maya was right to believe. The best hires prove themselves through work.",
      userId: "demo-nova",
      inferredMode: "Proud",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Team success",
      loops: "",
      nextAction: "Celebrate his win",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "New hire delivered impressive results",
      actionableInsightsAI: "Bet on potential, let results prove it",
      entryLengthWords: 48,
      daysSinceEntry: 22,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["team", "achievement", "growth"],
      createdTime: "2025-12-26T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-41",
      name: "10K MRR Milestone",
      type: "Work",
      date: "2025-12-26",
      timestamp: "2025-12-26T06:00:00Z",
      text: "We crossed $10K MRR. Tiny by VC standards. Massive for us. Six months ago this was a Figma prototype. Now it's a business. Real revenue. Real customers. Real company. The small milestones deserve celebration too.",
      userId: "demo-nova",
      inferredMode: "Proud",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Growth vs. Comfort",
      snapshot: "Revenue milestone",
      loops: "",
      nextAction: "Push to 50K",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Reached $10K monthly recurring revenue",
      actionableInsightsAI: "Celebrate milestones while pushing forward",
      entryLengthWords: 48,
      daysSinceEntry: 22,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["revenue", "milestone", "growth"],
      createdTime: "2025-12-26T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-42",
      name: "Work-Life Attempt",
      type: "Health",
      date: "2025-12-26",
      timestamp: "2025-12-26T12:00:00Z",
      text: "Took Sunday off. Actually off. No Slack. No email. Went hiking. Brain kept trying to solve work problems. But by the end, I was just... walking. Being. The company survived 8 hours without me. It can survive more.",
      userId: "demo-nova",
      inferredMode: "Refreshed",
      inferredEnergy: "Balanced",
      energyShape: "Flowing",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Rest day",
      loops: "Difficulty disconnecting",
      nextAction: "Schedule regular breaks",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Successfully took day off despite difficulty",
      actionableInsightsAI: "Companies survive founder breaks",
      entryLengthWords: 50,
      daysSinceEntry: 23,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["rest", "balance", "self-care"],
      createdTime: "2025-12-26T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-43",
      name: "Week Six Summary",
      type: "Reflection",
      date: "2025-12-25",
      timestamp: "2025-12-25T18:00:00Z",
      text: "Six weeks of journaling. From panic to purpose. From rejection to revenue. From solo anxiety to shared journey. Still hard. Still scary. But also: clear mission, good team, growing revenue, funded runway. This is working.",
      userId: "demo-nova",
      inferredMode: "Hopeful",
      inferredEnergy: "Balanced",
      energyShape: "Rising",
      contradiction: "Growth vs. Comfort",
      snapshot: "Six week reflection",
      loops: "",
      nextAction: "Keep building",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Six weeks transformed fear into foundation",
      actionableInsightsAI: "Progress is visible in retrospect",
      entryLengthWords: 48,
      daysSinceEntry: 23,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["reflection", "growth", "progress"],
      createdTime: "2025-12-25T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "nova-44",
      name: "Mentor Proud Moment",
      type: "Family",
      date: "2025-12-25",
      timestamp: "2025-12-25T22:00:00Z",
      text: "David said he's proud of how I've handled the last month. Coming from him, that means everything. He's seen hundreds of founders. If he thinks I'm doing okay, maybe I am. External validation shouldn't matter. But it does.",
      userId: "demo-nova",
      inferredMode: "Validated",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Mentor recognition",
      loops: "",
      nextAction: "Internalize the confidence",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Mentor validation provided confidence boost",
      actionableInsightsAI: "Experienced perspective offers valuable calibration",
      entryLengthWords: 50,
      daysSinceEntry: 24,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["mentorship", "validation", "confidence"],
      createdTime: "2025-12-25T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "nova-45",
      name: "Looking Forward",
      type: "Reflection",
      date: "2025-12-25",
      timestamp: "2025-12-25T06:00:00Z",
      text: "What's next? Series A in 18 months. Team of 20. $1M ARR. Big goals. Scary goals. But I'm not alone anymore. We have money, mission, and people. The startup journey continues. One day, one customer, one feature at a time.",
      userId: "demo-nova",
      inferredMode: "Determined",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Past vs. Present",
      snapshot: "Future vision",
      loops: "",
      nextAction: "Execute",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Clear-eyed view of ambitious future goals",
      actionableInsightsAI: "Big goals achieved through small steps",
      entryLengthWords: 50,
      daysSinceEntry: 43,
      isRecent: false,
      sentimentAI: "Positive",
      themeTagsAI: ["vision", "goals", "determination"],
      createdTime: "2025-12-25T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
  ]
}
