// Sherlock Holmes Demo Data - Detective themed entries
import type { Entry } from "../airtable"

export function getSherlockDemoData(): Entry[] {
  return [
    // Week 1 - New Case Intrigue
    {
      id: "sherlock-1",
      name: "The Whitechapel Cipher",
      type: "Work",
      date: "2026-01-08",
      timestamp: "2026-01-08T06:00:00Z",
      text: "A new case arrived today. Encrypted letters found in a deceased banker's vault. Scotland Yard is baffled, naturally. The cipher uses a substitution pattern I've seen once before - in a treatise on medieval cryptography. The game is afoot.",
      userId: "demo-sherlock",
      inferredMode: "Energized",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Logic vs. Faith",
      snapshot: "Case begins",
      loops: "",
      nextAction: "Analyze cipher patterns",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "New cryptographic case energizes Holmes",
      actionableInsightsAI: "Past knowledge informs current puzzles",
      entryLengthWords: 50,
      daysSinceEntry: 0,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["mystery", "cryptography", "excitement"],
      createdTime: "2026-01-08T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-2",
      name: "Watson's Observations",
      type: "Family",
      date: "2026-01-08",
      timestamp: "2026-01-08T12:00:00Z",
      text: "Watson commented today that I seem 'more alive' when working cases. He's not wrong. The ordinary world is unbearably tedious. Every mind needs a worthy opponent - mine simply requires more than most. Is that arrogance or honesty?",
      userId: "demo-sherlock",
      inferredMode: "Contemplative",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Self-reflection",
      loops: "Identity patterns",
      nextAction: "Consider Watson's words",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Reflecting on Watson's observation about purpose",
      actionableInsightsAI: "Others see us more clearly sometimes",
      entryLengthWords: 48,
      daysSinceEntry: 1,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["friendship", "self-awareness", "purpose"],
      createdTime: "2026-01-08T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-3",
      name: "The Seven Percent Solution",
      type: "Health",
      date: "2026-01-08",
      timestamp: "2026-01-08T18:00:00Z",
      text: "Could not sleep. The old urge returned - the needle, the solution. Watson hid my supplies months ago. He thinks I don't know where. I do. But I did not go to them tonight. Progress, perhaps. Or merely postponement.",
      userId: "demo-sherlock",
      inferredMode: "Struggling",
      inferredEnergy: "Low",
      energyShape: "Chaotic",
      contradiction: "Growth vs. Comfort",
      snapshot: "Addiction temptation",
      loops: "Addiction patterns",
      nextAction: "Find healthier stimulation",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Resisted addiction urges during sleepless night",
      actionableInsightsAI: "Resisting urges is its own victory",
      entryLengthWords: 50,
      daysSinceEntry: 1,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["addiction", "struggle", "recovery"],
      createdTime: "2026-01-08T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-4",
      name: "Violin Composition",
      type: "Creativity",
      date: "2026-01-07",
      timestamp: "2026-01-07T22:00:00Z",
      text: "Composed a new piece tonight. Minor key, melancholic. Mrs. Hudson complained. Watson listened. The violin speaks what words cannot. Music is merely mathematics made audible - and mathematics is merely truth made visible.",
      userId: "demo-sherlock",
      inferredMode: "Creative",
      inferredEnergy: "Moderate",
      energyShape: "Flowing",
      contradiction: "Closeness vs. Distance",
      snapshot: "Musical expression",
      loops: "",
      nextAction: "Continue composing",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Found emotional expression through violin",
      actionableInsightsAI: "Art provides outlet for unspoken feelings",
      entryLengthWords: 42,
      daysSinceEntry: 2,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["music", "expression", "creativity"],
      createdTime: "2026-01-07T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-5",
      name: "Mrs. Hudson's Patience",
      type: "Family",
      date: "2026-01-07",
      timestamp: "2026-01-07T06:00:00Z",
      text: "Mrs. Hudson brought tea despite my experiments having stained her good tablecloth with sulfuric acid. She said nothing - merely sighed. This woman has endured more from me than any saint could claim. I should... thank her. Sometime.",
      userId: "demo-sherlock",
      inferredMode: "Guilty",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Closeness vs. Distance",
      snapshot: "Gratitude moment",
      loops: "Taking others for granted",
      nextAction: "Express appreciation",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Recognized Mrs. Hudson's patient care",
      actionableInsightsAI: "Notice those who support without complaint",
      entryLengthWords: 48,
      daysSinceEntry: 2,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["gratitude", "relationships", "care"],
      createdTime: "2026-01-07T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-6",
      name: "The Cipher Breaks",
      type: "Work",
      date: "2026-01-07",
      timestamp: "2026-01-07T12:00:00Z",
      text: "EUREKA! The cipher was a book code - the key text being Montague's treatise on banking law. The letters reveal an embezzlement scheme spanning three continents. The deceased banker was murdered by his partners. Now to prove it.",
      userId: "demo-sherlock",
      inferredMode: "Triumphant",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Logic vs. Faith",
      snapshot: "Breakthrough moment",
      loops: "",
      nextAction: "Gather evidence",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Cracked cipher revealing murder conspiracy",
      actionableInsightsAI: "Persistence breaks the toughest codes",
      entryLengthWords: 46,
      daysSinceEntry: 3,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["breakthrough", "deduction", "triumph"],
      createdTime: "2026-01-07T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-7",
      name: "London at Night",
      type: "Reflection",
      date: "2026-01-06",
      timestamp: "2026-01-06T18:00:00Z",
      text: "Walked the foggy streets alone. Every lit window a story. Every shadow a possibility. London is a vast organism of secrets - and I, its tireless cataloguer. There is poetry in this work, even if I struggle to express it.",
      userId: "demo-sherlock",
      inferredMode: "Contemplative",
      inferredEnergy: "Low",
      energyShape: "Flowing",
      contradiction: "Closeness vs. Distance",
      snapshot: "Night wandering",
      loops: "",
      nextAction: "Rest eventually",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Philosophical night walk through London",
      actionableInsightsAI: "Beauty exists in the work of observation",
      entryLengthWords: 48,
      daysSinceEntry: 3,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["London", "observation", "poetry"],
      createdTime: "2026-01-06T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 2 - Case Breakthrough
    {
      id: "sherlock-8",
      name: "Confronting the Suspects",
      type: "Work",
      date: "2026-01-06",
      timestamp: "2026-01-06T22:00:00Z",
      text: "Met with the three partners today. Each believes the others guilty. Their tells were unmistakable - the nervous eye movement of Blackwood, the rehearsed calm of Morrison, the genuine shock of Hayes. Hayes is innocent. The other two are not.",
      userId: "demo-sherlock",
      inferredMode: "Analytical",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Logic vs. Faith",
      snapshot: "Interrogation",
      loops: "",
      nextAction: "Trap Blackwood and Morrison",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Identified guilty parties through behavioral analysis",
      actionableInsightsAI: "Body language reveals what words conceal",
      entryLengthWords: 50,
      daysSinceEntry: 4,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["deduction", "interrogation", "truth"],
      createdTime: "2026-01-06T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-9",
      name: "Watson's Medical Opinion",
      type: "Health",
      date: "2026-01-06",
      timestamp: "2026-01-06T06:00:00Z",
      text: "Watson insisted on checking my vital signs. Three days without proper food, he noted. When did I last eat? I cannot recall. The body is transport for the mind - but perhaps I've been neglecting the vehicle. He made soup. I ate.",
      userId: "demo-sherlock",
      inferredMode: "Reluctant",
      inferredEnergy: "Drained",
      energyShape: "Heavy",
      contradiction: "Logic vs. Faith",
      snapshot: "Self-neglect called out",
      loops: "Neglecting physical needs",
      nextAction: "Eat regularly",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Watson intervened about Holmes's self-neglect",
      actionableInsightsAI: "Mind requires a functioning body",
      entryLengthWords: 52,
      daysSinceEntry: 4,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["health", "friendship", "care"],
      createdTime: "2026-01-06T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-10",
      name: "The Trap is Set",
      type: "Work",
      date: "2026-01-05",
      timestamp: "2026-01-05T12:00:00Z",
      text: "Sent identical letters to Blackwood and Morrison - each suggesting the other is about to confess. They will meet at the docks tonight to eliminate their 'liability.' Lestrade and his men will be waiting. Predictable criminals are my favorite.",
      userId: "demo-sherlock",
      inferredMode: "Confident",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Competition vs. Collaboration",
      snapshot: "Trap laid",
      loops: "",
      nextAction: "Attend the arrest",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Orchestrated trap to catch guilty parties",
      actionableInsightsAI: "Criminal predictability aids justice",
      entryLengthWords: 48,
      daysSinceEntry: 5,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["strategy", "trap", "justice"],
      createdTime: "2026-01-05T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-11",
      name: "A Letter from Mycroft",
      type: "Family",
      date: "2026-01-05",
      timestamp: "2026-01-05T18:00:00Z",
      text: "My brother writes to criticize my methods - says I take unnecessary risks. Coming from a man who never leaves his chair at the Diogenes Club. Our relationship exists in these passive aggressive notes. Perhaps that is enough. Perhaps not.",
      userId: "demo-sherlock",
      inferredMode: "Irritated",
      inferredEnergy: "Moderate",
      energyShape: "Uneven",
      contradiction: "Closeness vs. Distance",
      snapshot: "Sibling friction",
      loops: "Family avoidance",
      nextAction: "Ignore or respond?",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Mycroft's criticism provokes reflection on relationship",
      actionableInsightsAI: "Distant relationships still carry weight",
      entryLengthWords: 50,
      daysSinceEntry: 5,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["family", "criticism", "distance"],
      createdTime: "2026-01-05T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-12",
      name: "Case Closed",
      type: "Work",
      date: "2026-01-05",
      timestamp: "2026-01-05T22:00:00Z",
      text: "Blackwood and Morrison are in custody. They attempted to murder each other at the docks - how deliciously ironic. Lestrade will take credit in the papers, as always. The truth knows who solved it. That is sufficient.",
      userId: "demo-sherlock",
      inferredMode: "Satisfied",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Competition vs. Collaboration",
      snapshot: "Case resolution",
      loops: "",
      nextAction: "Find new challenge",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Successfully closed case with arrests",
      actionableInsightsAI: "Results matter more than recognition",
      entryLengthWords: 46,
      daysSinceEntry: 6,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["success", "justice", "satisfaction"],
      createdTime: "2026-01-05T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-13",
      name: "Post-Case Emptiness",
      type: "Emotional",
      date: "2026-01-04",
      timestamp: "2026-01-04T06:00:00Z",
      text: "The case is solved. And now... nothing. The flat feels smaller. The violin sounds hollow. This is the danger - the void after the hunt. Watson suggested a walk. I suggested being left alone. I fear I was unnecessarily harsh.",
      userId: "demo-sherlock",
      inferredMode: "Depressed",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Closeness vs. Distance",
      snapshot: "Post-case crash",
      loops: "Depression after success",
      nextAction: "Apologize to Watson",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Experiencing familiar post-case depression",
      actionableInsightsAI: "Success can precede emptiness",
      entryLengthWords: 50,
      daysSinceEntry: 6,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["depression", "emptiness", "regret"],
      createdTime: "2026-01-04T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-14",
      name: "Week One Summary",
      type: "Reflection",
      date: "2026-01-04",
      timestamp: "2026-01-04T12:00:00Z",
      text: "A week of triumph and its aftermath. Cipher cracked, murderers caught, justice served. And now the familiar descent. Watson says I should journal more between cases. Perhaps. If only to document the patterns I am too proud to admit.",
      userId: "demo-sherlock",
      inferredMode: "Reflective",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Growth vs. Comfort",
      snapshot: "Weekly reflection",
      loops: "",
      nextAction: "Try Watson's suggestion",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "First week ended with success but emptiness",
      actionableInsightsAI: "Patterns only improve when acknowledged",
      entryLengthWords: 48,
      daysSinceEntry: 7,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["reflection", "patterns", "growth"],
      createdTime: "2026-01-04T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 3 - Between Cases, Boredom
    {
      id: "sherlock-15",
      name: "Tedium of Tuesday",
      type: "Emotional",
      date: "2026-01-04",
      timestamp: "2026-01-04T18:00:00Z",
      text: "No cases. No puzzles. I reorganized my index of London criminals twice. Shot my initials into the wall with Watson's revolver. He was not pleased. The mind rots without stimulation. I feel myself decaying.",
      userId: "demo-sherlock",
      inferredMode: "Agitated",
      inferredEnergy: "High",
      energyShape: "Chaotic",
      contradiction: "Action vs. Rest",
      snapshot: "Boredom crisis",
      loops: "Destructive boredom",
      nextAction: "Find productive outlet",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Destructive behavior from lack of stimulation",
      actionableInsightsAI: "Boredom requires active management",
      entryLengthWords: 46,
      daysSinceEntry: 8,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["boredom", "agitation", "destructive"],
      createdTime: "2026-01-04T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-16",
      name: "New Year's Resolution",
      type: "Reflection",
      date: "2026-01-03",
      timestamp: "2026-01-03T22:00:00Z",
      text: "Watson insisted we mark the new year. Champagne. Reflection. He asked my resolution. I said 'To solve every case brought to me.' He smiled and said his was 'To keep you alive long enough to do so.' Insufferable. Irreplaceable.",
      userId: "demo-sherlock",
      inferredMode: "Touched",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Closeness vs. Distance",
      snapshot: "Friendship moment",
      loops: "",
      nextAction: "Value Watson more",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "New Year's moment of friendship appreciation",
      actionableInsightsAI: "Some people are irreplaceable",
      entryLengthWords: 50,
      daysSinceEntry: 8,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["friendship", "new year", "appreciation"],
      createdTime: "2026-01-03T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-17",
      name: "Chemical Experiments",
      type: "Creativity",
      date: "2026-01-03",
      timestamp: "2026-01-03T06:00:00Z",
      text: "Conducted experiments on blood coagulation rates under various conditions. Purely academic - no current case requires it. But knowledge stored is knowledge available. Watson called it 'morbid.' I call it preparation.",
      userId: "demo-sherlock",
      inferredMode: "Focused",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Logic vs. Faith",
      snapshot: "Research mode",
      loops: "",
      nextAction: "Document findings",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Self-directed research to combat boredom",
      actionableInsightsAI: "Preparation disguises as idle curiosity",
      entryLengthWords: 42,
      daysSinceEntry: 9,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["research", "preparation", "science"],
      createdTime: "2026-01-03T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-18",
      name: "A Minor Puzzle",
      type: "Work",
      date: "2026-01-03",
      timestamp: "2026-01-03T12:00:00Z",
      text: "A man came about his missing pocket watch. Hardly worth my time - yet I deduced it fell through a hole in his coat into the lining, currently residing at his tailor's shop. His amazement was disproportionate. Small victories for small days.",
      userId: "demo-sherlock",
      inferredMode: "Amused",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Growth vs. Comfort",
      snapshot: "Minor case",
      loops: "",
      nextAction: "Accept what comes",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Solved trivial case to stay sharp",
      actionableInsightsAI: "Small problems still exercise the mind",
      entryLengthWords: 50,
      daysSinceEntry: 9,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["deduction", "amusement", "small victories"],
      createdTime: "2026-01-03T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-19",
      name: "Reading Watson's Stories",
      type: "Cognitive",
      date: "2026-01-02",
      timestamp: "2026-01-02T18:00:00Z",
      text: "Watson showed me his latest story for The Strand - a dramatic retelling of the cipher case. He romanticizes everything. I am portrayed as some sort of wizard rather than a methodical scientist. Yet... his stories reach people mine never would.",
      userId: "demo-sherlock",
      inferredMode: "Ambivalent",
      inferredEnergy: "Low",
      energyShape: "Uneven",
      contradiction: "Logic vs. Faith",
      snapshot: "Evaluating Watson's work",
      loops: "",
      nextAction: "Acknowledge his contribution",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Mixed feelings about Watson's storytelling style",
      actionableInsightsAI: "Different talents serve different purposes",
      entryLengthWords: 50,
      daysSinceEntry: 10,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["storytelling", "partnership", "appreciation"],
      createdTime: "2026-01-02T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-20",
      name: "The Baskerville Letter",
      type: "Work",
      date: "2026-01-02",
      timestamp: "2026-01-02T22:00:00Z",
      text: "An intriguing letter from Devonshire. A doctor Mortimer writes of a legendary hound and a dead baronet. Probably superstitious nonsense. Yet the details trouble me. Dogs that kill, curses that persist. Tomorrow, I meet this doctor.",
      userId: "demo-sherlock",
      inferredMode: "Intrigued",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Logic vs. Faith",
      snapshot: "New case brewing",
      loops: "",
      nextAction: "Interview Dr. Mortimer",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Potential new case captures interest",
      actionableInsightsAI: "Mystery energizes the sluggish mind",
      entryLengthWords: 48,
      daysSinceEntry: 10,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["mystery", "curiosity", "new case"],
      createdTime: "2026-01-02T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-21",
      name: "Week Two Summary",
      type: "Reflection",
      date: "2026-01-02",
      timestamp: "2026-01-02T06:00:00Z",
      text: "A week of waiting ended with possibility. The boredom nearly consumed me - Watson's patience alone kept me from worse choices. And now, a hound in Devonshire. A curse. A death. My blood stirs. The game may soon be afoot again.",
      userId: "demo-sherlock",
      inferredMode: "Hopeful",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Action vs. Rest",
      snapshot: "Weekly reflection",
      loops: "",
      nextAction: "Prepare for Devonshire",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Difficult week of boredom ends with new case",
      actionableInsightsAI: "Patience sometimes precedes opportunity",
      entryLengthWords: 50,
      daysSinceEntry: 11,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["patience", "anticipation", "renewal"],
      createdTime: "2026-01-02T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 4 - Challenging Adversary
    {
      id: "sherlock-22",
      name: "The Moor Reveals Nothing",
      type: "Work",
      date: "2026-01-01",
      timestamp: "2026-01-01T12:00:00Z",
      text: "Arrived at Baskerville Hall. The moor is oppressive, ancient, hiding secrets in its fog. No supernatural hound awaits - I am certain. Yet something hunts these lands. Something human. Someone clever. Finally, a worthy opponent.",
      userId: "demo-sherlock",
      inferredMode: "Alert",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Logic vs. Faith",
      snapshot: "Investigation begins",
      loops: "",
      nextAction: "Map the suspects",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Arrived at Baskerville convinced of human culprit",
      actionableInsightsAI: "Supernatural claims usually have earthly causes",
      entryLengthWords: 48,
      daysSinceEntry: 12,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["investigation", "deduction", "anticipation"],
      createdTime: "2026-01-01T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-23",
      name: "Watson on the Moor",
      type: "Family",
      date: "2026-01-01",
      timestamp: "2026-01-01T18:00:00Z",
      text: "Sent Watson ahead to Baskerville while I remained in London - officially. In truth, I observe from a hidden position on the moor. He reports admirably, though misses crucial details. His heart is his greatest asset and limitation.",
      userId: "demo-sherlock",
      inferredMode: "Calculating",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Closeness vs. Distance",
      snapshot: "Strategic positioning",
      loops: "",
      nextAction: "Continue surveillance",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Operating covertly while Watson reports openly",
      actionableInsightsAI: "Partners complement different perspectives",
      entryLengthWords: 48,
      daysSinceEntry: 12,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["strategy", "partnership", "deception"],
      createdTime: "2026-01-01T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-24",
      name: "Stapleton's Deception",
      type: "Cognitive",
      date: "2026-01-01",
      timestamp: "2026-01-01T22:00:00Z",
      text: "The naturalist Stapleton interests me. Too helpful. Too knowledgeable about the legend. His butterfly nets hide something more sinister. I've seen his type before - the charming monster behind friendly eyes. He is my adversary.",
      userId: "demo-sherlock",
      inferredMode: "Suspicious",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Logic vs. Faith",
      snapshot: "Suspect identified",
      loops: "",
      nextAction: "Prove Stapleton's guilt",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Identified Stapleton as primary suspect",
      actionableInsightsAI: "Excessive helpfulness can signal guilt",
      entryLengthWords: 50,
      daysSinceEntry: 13,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["suspicion", "adversary", "analysis"],
      createdTime: "2026-01-01T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-25",
      name: "Doubt in the Dark",
      type: "Emotional",
      date: "2025-12-31",
      timestamp: "2025-12-31T06:00:00Z",
      text: "Sleepless on the moor. Watson faces danger while I watch from shadows. If my deductions are wrong, an innocent man dies. The responsibility is crushing. I claim certainty but tonight I feel the weight of fallibility.",
      userId: "demo-sherlock",
      inferredMode: "Anxious",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Self-doubt moment",
      loops: "Fear of failure",
      nextAction: "Trust the method",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Rare moment of self-doubt about deductions",
      actionableInsightsAI: "Doubt keeps confidence from becoming arrogance",
      entryLengthWords: 48,
      daysSinceEntry: 13,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["doubt", "responsibility", "fear"],
      createdTime: "2025-12-31T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-26",
      name: "The Hound Appears",
      type: "Work",
      date: "2025-12-31",
      timestamp: "2025-12-31T12:00:00Z",
      text: "I saw it. A hound - enormous, phosphorescent, bounding across the moor. For one second my rational mind wavered. Then I understood: phosphorus paint on a real dog. Stapleton's theatrical genius. Tomorrow, this ends.",
      userId: "demo-sherlock",
      inferredMode: "Determined",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Logic vs. Faith",
      snapshot: "Mystery solved",
      loops: "",
      nextAction: "Confront Stapleton",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Discovered trick behind supernatural hound",
      actionableInsightsAI: "Rational explanations exist for seemingly impossible events",
      entryLengthWords: 46,
      daysSinceEntry: 14,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["revelation", "triumph", "rationality"],
      createdTime: "2025-12-31T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-27",
      name: "Christmas on the Moor",
      type: "Reflection",
      date: "2025-12-31",
      timestamp: "2025-12-31T18:00:00Z",
      text: "Christmas Day spent in a stone hut on a foggy moor. Watson is at the Hall enjoying festive meals. I am here with cold ham and colder contemplation. Yet I would not trade this. The chase is my celebration.",
      userId: "demo-sherlock",
      inferredMode: "Content",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Solitary holiday",
      loops: "",
      nextAction: "Solve the case",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Spent Christmas alone pursuing justice",
      actionableInsightsAI: "Purpose provides its own celebration",
      entryLengthWords: 48,
      daysSinceEntry: 14,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["solitude", "purpose", "dedication"],
      createdTime: "2025-12-31T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-28",
      name: "Week Three Summary",
      type: "Reflection",
      date: "2025-12-30",
      timestamp: "2025-12-30T22:00:00Z",
      text: "Week three in Devonshire. A worthy adversary found and understood. Tomorrow brings confrontation. The pieces align. Stapleton will hang for his crimes. And I will return to London having tested myself against darkness once more.",
      userId: "demo-sherlock",
      inferredMode: "Resolute",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Action vs. Fear",
      snapshot: "Pre-finale reflection",
      loops: "",
      nextAction: "Execute the plan",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Third week ended with case solution pending execution",
      actionableInsightsAI: "Preparation enables confident action",
      entryLengthWords: 46,
      daysSinceEntry: 15,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["resolution", "anticipation", "confidence"],
      createdTime: "2025-12-30T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 5 - Case Resolution
    {
      id: "sherlock-29",
      name: "Stapleton Falls",
      type: "Work",
      date: "2025-12-30",
      timestamp: "2025-12-30T06:00:00Z",
      text: "Stapleton fled into the Grimpen Mire when cornered. The bog claimed him before justice could. The hound is dead - shot by Watson with admirable accuracy. Sir Henry is safe. The case is closed, though not as neatly as I'd prefer.",
      userId: "demo-sherlock",
      inferredMode: "Mixed",
      inferredEnergy: "Moderate",
      energyShape: "Uneven",
      contradiction: "Justice vs. Mercy",
      snapshot: "Case conclusion",
      loops: "",
      nextAction: "Write the report",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Case ended with villain's death in mire",
      actionableInsightsAI: "Not all resolutions are clean",
      entryLengthWords: 50,
      daysSinceEntry: 16,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["conclusion", "justice", "imperfection"],
      createdTime: "2025-12-30T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-30",
      name: "Watson's Bravery",
      type: "Family",
      date: "2025-12-30",
      timestamp: "2025-12-30T12:00:00Z",
      text: "Watson shot the hound mid-charge. Saved Sir Henry's life. His hands shook afterwards - not from fear but adrenaline. The man is no detective, but his courage exceeds mine in ways I rarely acknowledge. I should tell him.",
      userId: "demo-sherlock",
      inferredMode: "Grateful",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Closeness vs. Distance",
      snapshot: "Appreciating Watson",
      loops: "",
      nextAction: "Express gratitude",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Reflecting on Watson's brave actions",
      actionableInsightsAI: "Acknowledge others' contributions aloud",
      entryLengthWords: 48,
      daysSinceEntry: 17,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["gratitude", "courage", "friendship"],
      createdTime: "2025-12-30T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-31",
      name: "Return to Baker Street",
      type: "Health",
      date: "2025-12-29",
      timestamp: "2025-12-29T18:00:00Z",
      text: "Back at 221B. Mrs. Hudson had prepared a fire and left soup. The familiar chaos of my papers, my chemicals, my indices. Home is this: a place that tolerates who I am without demanding I become someone else.",
      userId: "demo-sherlock",
      inferredMode: "Relieved",
      inferredEnergy: "Low",
      energyShape: "Stabilized",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Homecoming",
      loops: "",
      nextAction: "Rest properly",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Relief at returning to familiar Baker Street",
      actionableInsightsAI: "Home is where we are accepted",
      entryLengthWords: 48,
      daysSinceEntry: 17,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["home", "comfort", "acceptance"],
      createdTime: "2025-12-29T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-32",
      name: "The Emptiness Returns",
      type: "Emotional",
      date: "2025-12-29",
      timestamp: "2025-12-29T22:00:00Z",
      text: "And so it comes again. The void after victory. The violin cannot fill it tonight. I pace. I consider the needle. Watson is asleep. The temptation whispers. Not tonight. Not tonight. I will read instead. Something tedious. Tax law.",
      userId: "demo-sherlock",
      inferredMode: "Vulnerable",
      inferredEnergy: "Low",
      energyShape: "Chaotic",
      contradiction: "Growth vs. Comfort",
      snapshot: "Fighting temptation",
      loops: "Post-case depression",
      nextAction: "Distract until dawn",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Fighting addiction urges in post-case emptiness",
      actionableInsightsAI: "Distraction is a valid recovery tool",
      entryLengthWords: 52,
      daysSinceEntry: 18,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["temptation", "struggle", "resistance"],
      createdTime: "2025-12-29T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-33",
      name: "A Thank You Note",
      type: "Family",
      date: "2025-12-29",
      timestamp: "2025-12-29T06:00:00Z",
      text: "Wrote Watson a note. Three sentences expressing gratitude for Devonshire. Left it on his desk. I could not say it aloud. But writing it felt... necessary. He found it. Smiled. Said nothing. Knew better than to make a scene.",
      userId: "demo-sherlock",
      inferredMode: "Awkward",
      inferredEnergy: "Moderate",
      energyShape: "Uneven",
      contradiction: "Closeness vs. Distance",
      snapshot: "Expressing gratitude",
      loops: "",
      nextAction: "Practice this more",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Expressed gratitude to Watson in writing",
      actionableInsightsAI: "Written appreciation counts too",
      entryLengthWords: 50,
      daysSinceEntry: 18,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["gratitude", "growth", "vulnerability"],
      createdTime: "2025-12-29T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-34",
      name: "The Mind Wants Problems",
      type: "Cognitive",
      date: "2025-12-28",
      timestamp: "2025-12-28T12:00:00Z",
      text: "Analyzed Watson's stories for logical errors. Found seventeen in three hours. He accused me of cruelty. Perhaps. But the mind must work or wither. I apologized - a rare occurrence. He forgave - a common one.",
      userId: "demo-sherlock",
      inferredMode: "Restless",
      inferredEnergy: "High",
      energyShape: "Chaotic",
      contradiction: "Closeness vs. Distance",
      snapshot: "Misdirected energy",
      loops: "Criticizing others when bored",
      nextAction: "Channel energy elsewhere",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Criticized Watson then apologized",
      actionableInsightsAI: "Restless minds can hurt those nearby",
      entryLengthWords: 48,
      daysSinceEntry: 19,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["restlessness", "apology", "growth"],
      createdTime: "2025-12-28T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-35",
      name: "Week Four Summary",
      type: "Reflection",
      date: "2025-12-28",
      timestamp: "2025-12-28T18:00:00Z",
      text: "Week four. Case closed, demons battled, gratitude expressed. The cycle continues - thrill to void to restlessness to renewal. Watson says I should write during the valleys. These words are the attempt. Whether they help remains uncertain.",
      userId: "demo-sherlock",
      inferredMode: "Analytical",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Weekly reflection",
      loops: "",
      nextAction: "Continue writing",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Fourth week of journaling shows patterns",
      actionableInsightsAI: "Awareness of cycles helps navigate them",
      entryLengthWords: 48,
      daysSinceEntry: 19,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["reflection", "patterns", "growth"],
      createdTime: "2025-12-28T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 6 - Quiet Reflection
    {
      id: "sherlock-36",
      name: "Moriarty Rumors",
      type: "Work",
      date: "2025-12-28",
      timestamp: "2025-12-28T22:00:00Z",
      text: "Mycroft sent word of a criminal network. A spider at its center - a professor of mathematics. 'Moriarty,' they call him. A mind like mine, turned to evil. If such an adversary exists, he would be... magnificent. Terrifying. Necessary.",
      userId: "demo-sherlock",
      inferredMode: "Intrigued",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Competition vs. Collaboration",
      snapshot: "Future threat",
      loops: "",
      nextAction: "Investigate quietly",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Learning of potential master criminal Moriarty",
      actionableInsightsAI: "Great challenges can be both threat and purpose",
      entryLengthWords: 50,
      daysSinceEntry: 20,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["adversary", "anticipation", "danger"],
      createdTime: "2025-12-28T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-37",
      name: "Tea with Mrs. Hudson",
      type: "Family",
      date: "2025-12-27",
      timestamp: "2025-12-27T06:00:00Z",
      text: "Mrs. Hudson insisted I join her for tea. Talked of her late husband, her fears for my health, her pride in keeping house for 'London's greatest detective.' I said little but listened much. Kindness freely given deserves presence freely returned.",
      userId: "demo-sherlock",
      inferredMode: "Attentive",
      inferredEnergy: "Low",
      energyShape: "Flowing",
      contradiction: "Closeness vs. Distance",
      snapshot: "Quiet connection",
      loops: "",
      nextAction: "Have tea more often",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Meaningful conversation with Mrs. Hudson",
      actionableInsightsAI: "Presence is its own form of gratitude",
      entryLengthWords: 50,
      daysSinceEntry: 20,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["connection", "kindness", "presence"],
      createdTime: "2025-12-27T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-38",
      name: "The Violin Speaks",
      type: "Creativity",
      date: "2025-12-27",
      timestamp: "2025-12-27T12:00:00Z",
      text: "Played Mendelssohn tonight - the entire Violin Concerto from memory. Watson listened. When I finished, neither spoke. The music had said enough. Some communications transcend words. Perhaps that is why I prefer the violin to conversation.",
      userId: "demo-sherlock",
      inferredMode: "Expressive",
      inferredEnergy: "Moderate",
      energyShape: "Flowing",
      contradiction: "Closeness vs. Distance",
      snapshot: "Musical connection",
      loops: "",
      nextAction: "Play more for Watson",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Connected with Watson through music",
      actionableInsightsAI: "Art communicates what words cannot",
      entryLengthWords: 48,
      daysSinceEntry: 21,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["music", "connection", "expression"],
      createdTime: "2025-12-27T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-39",
      name: "On Friendship",
      type: "Reflection",
      date: "2025-12-27",
      timestamp: "2025-12-27T18:00:00Z",
      text: "Watson asked why I never married. I said work precludes such attachments. The truth is more complex. Romantic love seems inefficient. But friendship - Watson's friendship - provides what I need without demanding what I cannot give.",
      userId: "demo-sherlock",
      inferredMode: "Honest",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Closeness vs. Distance",
      snapshot: "Relationship philosophy",
      loops: "",
      nextAction: "Maintain what works",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Reflecting on value of friendship over romance",
      actionableInsightsAI: "Different relationships serve different needs",
      entryLengthWords: 48,
      daysSinceEntry: 21,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["friendship", "relationships", "honesty"],
      createdTime: "2025-12-27T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-40",
      name: "One Week Clean",
      type: "Health",
      date: "2025-12-26",
      timestamp: "2025-12-26T22:00:00Z",
      text: "Seven days since I last considered the needle seriously. Watson noticed I've been eating regularly. Mrs. Hudson noted I'm 'less frightening.' Perhaps the journaling helps. Perhaps it's random variation. I choose to believe the former.",
      userId: "demo-sherlock",
      inferredMode: "Cautiously Hopeful",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Growth vs. Comfort",
      snapshot: "Recovery progress",
      loops: "",
      nextAction: "Continue what works",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Milestone of recovery noticed by others",
      actionableInsightsAI: "Small changes accumulate into larger ones",
      entryLengthWords: 48,
      daysSinceEntry: 22,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["recovery", "progress", "hope"],
      createdTime: "2025-12-26T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-41",
      name: "The City Awakens",
      type: "Reflection",
      date: "2025-12-26",
      timestamp: "2025-12-26T06:00:00Z",
      text: "Watched London wake from my window. Hansom cabs, street vendors, the endless human parade. Each person a mystery. Each life a case unsolved. There is infinite work in this city for one who cares to see. I am never truly without purpose.",
      userId: "demo-sherlock",
      inferredMode: "Philosophical",
      inferredEnergy: "Low",
      energyShape: "Expanding",
      contradiction: "Past vs. Present",
      snapshot: "Morning observation",
      loops: "",
      nextAction: "Stay curious",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Found purpose in London's endless mysteries",
      actionableInsightsAI: "Purpose exists everywhere for those who look",
      entryLengthWords: 50,
      daysSinceEntry: 22,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["purpose", "observation", "curiosity"],
      createdTime: "2025-12-26T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-42",
      name: "Letter to Mycroft",
      type: "Family",
      date: "2025-12-26",
      timestamp: "2025-12-26T12:00:00Z",
      text: "Responded to Mycroft's letter. Brief, civil, informative. Asked about our mother's estate matters. Did not mention his criticism of my methods. Perhaps maturity is knowing which battles to fight. Or perhaps I simply lacked the energy.",
      userId: "demo-sherlock",
      inferredMode: "Measured",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Closeness vs. Distance",
      snapshot: "Family communication",
      loops: "",
      nextAction: "Maintain contact",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Civil response to brother without conflict",
      actionableInsightsAI: "Some conflicts don't need resolution",
      entryLengthWords: 48,
      daysSinceEntry: 23,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["family", "maturity", "communication"],
      createdTime: "2025-12-26T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-43",
      name: "Week Six Summary",
      type: "Reflection",
      date: "2025-12-25",
      timestamp: "2025-12-25T18:00:00Z",
      text: "Six weeks of journaling. Watson's experiment continues. The patterns are clearer now - the cycles of thrill and void, the struggle with demons internal and external. I am not cured of anything. But I am... aware. That is something.",
      userId: "demo-sherlock",
      inferredMode: "Self-Aware",
      inferredEnergy: "Balanced",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Six week reflection",
      loops: "",
      nextAction: "Continue observing self",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Six weeks showed value of self-observation",
      actionableInsightsAI: "Awareness itself is progress",
      entryLengthWords: 48,
      daysSinceEntry: 23,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["awareness", "growth", "patterns"],
      createdTime: "2025-12-25T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "sherlock-44",
      name: "A Small Case",
      type: "Work",
      date: "2025-12-25",
      timestamp: "2025-12-25T22:00:00Z",
      text: "Solved a missing jewel case. Turned out to be in the lady's other handbag. Trivial. But she wept with relief. Watson says these small services have value too. Perhaps. The mind still craves Moriarty. But it accepts smaller meals.",
      userId: "demo-sherlock",
      inferredMode: "Accepting",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Growth vs. Comfort",
      snapshot: "Small service",
      loops: "",
      nextAction: "Accept what comes",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Finding value in solving minor cases",
      actionableInsightsAI: "Small help still matters to those helped",
      entryLengthWords: 50,
      daysSinceEntry: 24,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["service", "acceptance", "humility"],
      createdTime: "2025-12-25T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "sherlock-45",
      name: "Looking Forward",
      type: "Reflection",
      date: "2025-12-25",
      timestamp: "2025-12-25T06:00:00Z",
      text: "What awaits? Moriarty, perhaps. More cases, certainly. More battles with the needle, probably. But also more music, more Watson, more Mrs. Hudson's tea. The game continues. And as long as it does, so shall I.",
      userId: "demo-sherlock",
      inferredMode: "Resolute",
      inferredEnergy: "Balanced",
      energyShape: "Rising",
      contradiction: "Past vs. Present",
      snapshot: "Future outlook",
      loops: "",
      nextAction: "Play the game",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Balanced outlook on future challenges",
      actionableInsightsAI: "Life is a game worth playing",
      entryLengthWords: 46,
      daysSinceEntry: 43,
      isRecent: false,
      sentimentAI: "Positive",
      themeTagsAI: ["future", "balance", "purpose"],
      createdTime: "2025-12-25T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
  ]
}
