// Demo Personas Data Module
// Contains demo journal entries for different personas

import type { Entry } from "./airtable"
import type { DemoPersona } from "../hooks/useDemoPersona"
import { getKratosDemoData } from "./demoData/kratosData"
import { getSherlockDemoData } from "./demoData/sherlockData"
import { getNovaDemoData } from "./demoData/novaData"

// Type for demo entries that don't have the decomposition fields
type DemoEntryBase = Omit<Entry, "entryFormat" | "parentEntryId" | "isDecomposed" | "decompositionCount" | "sequenceOrder" | "approximateTime" | "overarchingTheme">

// Helper to add required fields with defaults to demo entries
function withDefaults(entries: DemoEntryBase[]): Entry[] {
  return entries.map(entry => ({
    ...entry,
    entryFormat: "Quick Log" as const,
    parentEntryId: null,
    isDecomposed: false,
    decompositionCount: 0,
    sequenceOrder: null,
    approximateTime: null,
    overarchingTheme: null,
  }))
}

/**
 * Get demo data for a specific persona
 */
export function getDemoData(persona: DemoPersona): Entry[] {
  switch (persona) {
    case "mario":
      return withDefaults(getMarioDemoData())
    case "kratos":
      return withDefaults(getKratosDemoData())
    case "sherlock":
      return withDefaults(getSherlockDemoData())
    case "nova":
      return withDefaults(getNovaDemoData())
    default:
      return withDefaults(getMarioDemoData())
  }
}

// Mario Demo Data - 45 entries spanning 6 weeks
function getMarioDemoData(): DemoEntryBase[] {
  return [
    // Week 1 - Castle Adventures & Bowser Encounters
    {
      id: "mario-1",
      name: "Another Castle, Another Disappointment",
      type: "Emotional",
      date: "2026-01-08",
      timestamp: "2026-01-08T06:00:00Z",
      text: "Fought through 8 worlds of Koopas and Goombas only to hear 'Your princess is in another castle' AGAIN. The frustration is real but I won't give up on Peach. Every failed rescue attempt teaches me something new about Bowser's tactics.",
      userId: "demo-mario",
      inferredMode: "Determined",
      inferredEnergy: "Drained",
      energyShape: "Heavy",
      contradiction: "Action vs. Fear",
      snapshot: "Post-castle frustration",
      loops: "Rescue mission patterns",
      nextAction: "Study castle layouts",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Experienced another failed rescue but maintaining determination",
      actionableInsightsAI: "Map out castle patterns to improve efficiency",
      entryLengthWords: 52,
      daysSinceEntry: 0,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["persistence", "frustration", "heroism"],
      createdTime: "2026-01-08T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-2",
      name: "Super Star Rush!",
      type: "Health",
      date: "2026-01-08",
      timestamp: "2026-01-08T12:00:00Z",
      text: "Found a Super Star today and felt INVINCIBLE! Ran through enemies without a care. Reminded me why I love my job as a plumber-turned-hero. That golden glow, the music speeding up - pure adrenaline!",
      userId: "demo-mario",
      inferredMode: "Joyful",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Power vs. Vulnerability",
      snapshot: "Star power moment",
      loops: "",
      nextAction: "Find more power-up locations",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Experienced the joy of Super Star invincibility",
      actionableInsightsAI: "Catalog star block locations for future runs",
      entryLengthWords: 43,
      daysSinceEntry: 1,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["power-ups", "joy", "invincibility"],
      createdTime: "2026-01-08T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-3",
      name: "Bowser's Taunts Getting to Me",
      type: "Cognitive",
      date: "2026-01-08",
      timestamp: "2026-01-08T18:00:00Z",
      text: "Bowser sent another threatening letter today. Says Peach will never be rescued. I know it's psychological warfare but some nights, the doubt creeps in. What if I'm not fast enough? Strong enough?",
      userId: "demo-mario",
      inferredMode: "Anxious",
      inferredEnergy: "Low",
      energyShape: "Chaotic",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Self-doubt moment",
      loops: "Imposter syndrome patterns",
      nextAction: "Talk to Luigi about feelings",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Struggling with self-doubt from Bowser's psychological attacks",
      actionableInsightsAI: "Remember past victories when doubt creeps in",
      entryLengthWords: 47,
      daysSinceEntry: 1,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["self-doubt", "anxiety", "mental health"],
      createdTime: "2026-01-08T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-4",
      name: "Pipe Maintenance Day",
      type: "Work",
      date: "2026-01-07",
      timestamp: "2026-01-07T22:00:00Z",
      text: "Spent the day doing actual plumbing work in Toad Town. It's easy to forget I have a real profession beyond hero duties. Fixed Mrs. Toad's kitchen sink and installed new pipes at the marketplace. Honest work feels grounding.",
      userId: "demo-mario",
      inferredMode: "Grounded",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Back to basics",
      loops: "",
      nextAction: "Schedule regular plumbing days",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Reconnected with original profession through plumbing work",
      actionableInsightsAI: "Balance hero duties with grounding activities",
      entryLengthWords: 45,
      daysSinceEntry: 2,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["work", "plumbing", "balance"],
      createdTime: "2026-01-07T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-5",
      name: "Fire Flower Experiment Gone Wrong",
      type: "Creativity",
      date: "2026-01-07",
      timestamp: "2026-01-07T06:00:00Z",
      text: "Tried combining a Fire Flower with a Super Mushroom. Instead of becoming a giant fire-breathing Mario, I just got really bad heartburn. Maybe Professor E. Gadd was right about not mixing power-ups. Lesson learned.",
      userId: "demo-mario",
      inferredMode: "Curious",
      inferredEnergy: "Moderate",
      energyShape: "Uneven",
      contradiction: "Growth vs. Comfort",
      snapshot: "Failed experiment",
      loops: "Experimentation patterns",
      nextAction: "Consult E. Gadd before experiments",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Power-up experiment failed but gained knowledge",
      actionableInsightsAI: "Document experiments for future reference",
      entryLengthWords: 44,
      daysSinceEntry: 2,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["experimentation", "learning", "power-ups"],
      createdTime: "2026-01-07T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-6",
      name: "Luigi Heart-to-Heart",
      type: "Family",
      date: "2026-01-07",
      timestamp: "2026-01-07T12:00:00Z",
      text: "Had a long talk with Luigi tonight. He confessed he feels like he's always in my shadow. It hurt to hear but I understand. Told him about my own fears and doubts. We're more alike than either of us realized.",
      userId: "demo-mario",
      inferredMode: "Reflective",
      inferredEnergy: "Balanced",
      energyShape: "Centered",
      contradiction: "Closeness vs. Distance",
      snapshot: "Brother bonding",
      loops: "Sibling dynamics",
      nextAction: "Include Luigi more in adventures",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Deep conversation with Luigi about feelings and identity",
      actionableInsightsAI: "Schedule regular check-ins with Luigi",
      entryLengthWords: 50,
      daysSinceEntry: 3,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["family", "vulnerability", "connection"],
      createdTime: "2026-01-07T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-7",
      name: "Morning Mushroom Meditation",
      type: "Health",
      date: "2026-01-06",
      timestamp: "2026-01-06T18:00:00Z",
      text: "Started a new morning routine - meditating in the Mushroom Forest before sunrise. The peaceful silence, broken only by Piranha Plants snoring, helps center me before the chaos of the day. 10 coins for my thoughts.",
      userId: "demo-mario",
      inferredMode: "Calm",
      inferredEnergy: "Low",
      energyShape: "Flowing",
      contradiction: "Self-Care vs. Obligation",
      snapshot: "Peaceful morning",
      loops: "",
      nextAction: "Continue morning practice",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Established new meditation practice in Mushroom Forest",
      actionableInsightsAI: "Protect morning routine as sacred time",
      entryLengthWords: 42,
      daysSinceEntry: 3,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["meditation", "self-care", "morning routine"],
      createdTime: "2026-01-06T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 2 - Power-ups & Mushroom Kingdom Exploration
    {
      id: "mario-8",
      name: "Warp Zone Discovery!",
      type: "Work",
      date: "2026-01-06",
      timestamp: "2026-01-06T22:00:00Z",
      text: "HUGE discovery today! Found a secret warp zone that skips 3 entire worlds. This could change everything for rescue missions. Sometimes looking beyond the obvious path reveals shortcuts you never imagined.",
      userId: "demo-mario",
      inferredMode: "Hopeful",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Growth vs. Comfort",
      snapshot: "Breakthrough moment",
      loops: "",
      nextAction: "Map all warp zone locations",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Discovered new warp zone with major strategic implications",
      actionableInsightsAI: "Always explore hidden areas systematically",
      entryLengthWords: 42,
      daysSinceEntry: 4,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["discovery", "strategy", "shortcuts"],
      createdTime: "2026-01-06T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-9",
      name: "Toad's Birthday Party",
      type: "Leisure",
      date: "2026-01-06",
      timestamp: "2026-01-06T06:00:00Z",
      text: "Attended Toad's birthday celebration. Dancing, cake, and no Bowser attacks for once! Reminded that life isn't all about rescue missions. These moments of joy with friends are what I'm fighting to protect.",
      userId: "demo-mario",
      inferredMode: "Joyful",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Celebration time",
      loops: "",
      nextAction: "Plan more social gatherings",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Enjoyed Toad's birthday party with friends",
      actionableInsightsAI: "Prioritize celebrating life's good moments",
      entryLengthWords: 41,
      daysSinceEntry: 4,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["friendship", "celebration", "joy"],
      createdTime: "2026-01-06T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-10",
      name: "Goomba Guilt",
      type: "Reflection",
      date: "2026-01-05",
      timestamp: "2026-01-05T12:00:00Z",
      text: "Sometimes I wonder about all the Goombas I've... jumped on. Do they have families? Dreams? Am I the hero of this story or just someone who stomps first and asks questions never? Heavy thoughts tonight.",
      userId: "demo-mario",
      inferredMode: "Conflicted",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Justice vs. Mercy",
      snapshot: "Moral questioning",
      loops: "Ethics reflection pattern",
      nextAction: "Research Goomba society",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Philosophical reflection on the ethics of combat",
      actionableInsightsAI: "Explore non-violent approaches when possible",
      entryLengthWords: 44,
      daysSinceEntry: 5,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["ethics", "reflection", "guilt"],
      createdTime: "2026-01-05T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-11",
      name: "New Kart Design Ideas",
      type: "Creativity",
      date: "2026-01-05",
      timestamp: "2026-01-05T18:00:00Z",
      text: "Sketched out ideas for a new racing kart. Thinking blue shell resistant bumpers and a star power boost tank. Racing season is coming up and I want to beat that smug look off Wario's face this year.",
      userId: "demo-mario",
      inferredMode: "Creative",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Competition vs. Collaboration",
      snapshot: "Design session",
      loops: "",
      nextAction: "Prototype bumper design",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Working on new kart designs for racing season",
      actionableInsightsAI: "Test prototypes before major tournaments",
      entryLengthWords: 44,
      daysSinceEntry: 5,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["creativity", "racing", "design"],
      createdTime: "2026-01-05T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-12",
      name: "Coin Economy Concerns",
      type: "Cognitive",
      date: "2026-01-05",
      timestamp: "2026-01-05T22:00:00Z",
      text: "Where do all these floating coins come from? Who's funding this? I've collected millions over the years but never questioned the economics. Is this sustainable? Need to talk to the Mushroom Kingdom Treasury.",
      userId: "demo-mario",
      inferredMode: "Overthinking",
      inferredEnergy: "Moderate",
      energyShape: "Chaotic",
      contradiction: "Logic vs. Faith",
      snapshot: "Existential pondering",
      loops: "Overthinking patterns",
      nextAction: "Let it go - some mysteries stay mysteries",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Questioning the fundamentals of coin-based economy",
      actionableInsightsAI: "Focus on what can be controlled",
      entryLengthWords: 43,
      daysSinceEntry: 6,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["overthinking", "economics", "curiosity"],
      createdTime: "2026-01-05T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-13",
      name: "Yoshi Reunion",
      type: "Family",
      date: "2026-01-04",
      timestamp: "2026-01-04T06:00:00Z",
      text: "Visited Yoshi Island today. My green friend remembered me instantly and we went on a ride through the valleys. The bond between us goes back to when I was just a baby. Some friendships transcend time.",
      userId: "demo-mario",
      inferredMode: "Grateful",
      inferredEnergy: "Elevated",
      energyShape: "Expanding",
      contradiction: "Past vs. Present",
      snapshot: "Nostalgic reunion",
      loops: "",
      nextAction: "Visit Yoshi more often",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Reconnected with Yoshi at Yoshi Island",
      actionableInsightsAI: "Nurture long-standing friendships",
      entryLengthWords: 45,
      daysSinceEntry: 6,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["friendship", "nostalgia", "connection"],
      createdTime: "2026-01-04T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-14",
      name: "Weekly Reflection: Week 1",
      type: "Reflection",
      date: "2026-01-04",
      timestamp: "2026-01-04T12:00:00Z",
      text: "First week of the new year complete. Failed one rescue, made one breakthrough, and had meaningful conversations with Luigi and Yoshi. Progress isn't linear. The castle will fall eventually. Patience, Mario.",
      userId: "demo-mario",
      inferredMode: "Reflective",
      inferredEnergy: "Balanced",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Week in review",
      loops: "",
      nextAction: "Set Week 2 intentions",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Reflected on first week's mixed progress",
      actionableInsightsAI: "Continue journaling for self-awareness",
      entryLengthWords: 41,
      daysSinceEntry: 7,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["reflection", "progress", "patience"],
      createdTime: "2026-01-04T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 3-6 entries continue in similar pattern...
    {
      id: "mario-15",
      name: "Rainbow Road Disaster",
      type: "Emotional",
      date: "2026-01-04",
      timestamp: "2026-01-04T18:00:00Z",
      text: "Fell off Rainbow Road 7 TIMES during practice. The shame. The frustration. Everyone saw. Toadette tried to comfort me but I just wanted to disappear into a warp pipe. Some days you're the star, some days you're the banana peel.",
      userId: "demo-mario",
      inferredMode: "Frustrated",
      inferredEnergy: "Drained",
      energyShape: "Heavy",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Racing failure",
      loops: "Performance anxiety",
      nextAction: "Practice Rainbow Road alone",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Embarrassing practice session on Rainbow Road",
      actionableInsightsAI: "Everyone has bad days - focus on tomorrow",
      entryLengthWords: 50,
      daysSinceEntry: 8,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["failure", "embarrassment", "resilience"],
      createdTime: "2026-01-04T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-16",
      name: "New Year's Eve with Friends",
      type: "Leisure",
      date: "2026-01-03",
      timestamp: "2026-01-03T22:00:00Z",
      text: "Watched the fireworks over Peach's Castle with everyone. Even got a letter from Peach saying she saw them too from her tower. Bittersweet. A new year means new chances to bring her home. Here's to next year.",
      userId: "demo-mario",
      inferredMode: "Hopeful",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Joy vs. Sadness",
      snapshot: "New Year's hope",
      loops: "",
      nextAction: "Make new year's rescue plan",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Celebrated New Year's Eve with hope for rescue",
      actionableInsightsAI: "Channel hope into concrete action plans",
      entryLengthWords: 46,
      daysSinceEntry: 8,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["celebration", "hope", "new beginnings"],
      createdTime: "2026-01-03T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-17",
      name: "Peach's Secret Letter",
      type: "Emotional",
      date: "2026-01-03",
      timestamp: "2026-01-03T06:00:00Z",
      text: "A Lakitu smuggled out a letter from Peach today. She wrote that she believes in me, that she knows I'll come. Her words are worth more than all the coins in the kingdom. I won't let her down.",
      userId: "demo-mario",
      inferredMode: "Determined",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Action vs. Fear",
      snapshot: "Motivational letter",
      loops: "",
      nextAction: "Plan next rescue attempt",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Received motivating letter from Princess Peach",
      actionableInsightsAI: "Keep motivational messages visible",
      entryLengthWords: 44,
      daysSinceEntry: 9,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["motivation", "love", "determination"],
      createdTime: "2026-01-03T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-18",
      name: "Training with Donkey Kong",
      type: "Health",
      date: "2026-01-03",
      timestamp: "2026-01-03T12:00:00Z",
      text: "DK and I had a workout session today. Barrel throwing, vine swinging, the works. He's come a long way from when we first met on those construction beams. Old rivals, new friends. Feeling stronger.",
      userId: "demo-mario",
      inferredMode: "Energized",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Competition vs. Collaboration",
      snapshot: "Training day",
      loops: "",
      nextAction: "Weekly training with DK",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Productive training session with Donkey Kong",
      actionableInsightsAI: "Exercise with accountability partners",
      entryLengthWords: 43,
      daysSinceEntry: 9,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["exercise", "friendship", "growth"],
      createdTime: "2026-01-03T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-19",
      name: "The 1-Up Philosophy",
      type: "Cognitive",
      date: "2026-01-02",
      timestamp: "2026-01-02T18:00:00Z",
      text: "Every time I get a 1-Up mushroom, I essentially gain another life. But am I the same Mario? Is the Mario who fell into lava truly gone? These questions keep me up at night. Luigi says I need a hobby.",
      userId: "demo-mario",
      inferredMode: "Overthinking",
      inferredEnergy: "Low",
      energyShape: "Chaotic",
      contradiction: "Logic vs. Faith",
      snapshot: "Existential crisis",
      loops: "Philosophical spirals",
      nextAction: "Accept the mystery",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Deep philosophical questioning about identity",
      actionableInsightsAI: "Some questions don't need answers",
      entryLengthWords: 48,
      daysSinceEntry: 10,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["philosophy", "identity", "existential"],
      createdTime: "2026-01-02T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-20",
      name: "Helping Toadsworth",
      type: "Work",
      date: "2026-01-02",
      timestamp: "2026-01-02T22:00:00Z",
      text: "Helped Toadsworth organize the castle archives today. Found old maps of Bowser's castle from decades ago. The layouts have changed but some secret passages remain. This could be invaluable intel.",
      userId: "demo-mario",
      inferredMode: "Focused",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Past vs. Present",
      snapshot: "Research day",
      loops: "",
      nextAction: "Study old castle maps",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Found valuable historical intel in castle archives",
      actionableInsightsAI: "Historical knowledge can inform future strategy",
      entryLengthWords: 40,
      daysSinceEntry: 10,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["research", "strategy", "history"],
      createdTime: "2026-01-02T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-21",
      name: "Dream About Flying",
      type: "Reflection",
      date: "2026-01-02",
      timestamp: "2026-01-02T06:00:00Z",
      text: "Had a vivid dream where I had a cape and could fly anywhere. No castles, no Bowser, just endless blue sky. Woke up feeling both peaceful and sad. Sometimes I wonder what a simple life would feel like.",
      userId: "demo-mario",
      inferredMode: "Melancholic",
      inferredEnergy: "Low",
      energyShape: "Flowing",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Dream reflection",
      loops: "Escape fantasies",
      nextAction: "Honor the dream's message",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Reflected on dreams of freedom and simpler life",
      actionableInsightsAI: "Create space for freedom within current life",
      entryLengthWords: 47,
      daysSinceEntry: 11,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["dreams", "freedom", "longing"],
      createdTime: "2026-01-02T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-22",
      name: "Bowser Jr. Encounter",
      type: "Emotional",
      date: "2026-01-01",
      timestamp: "2026-01-01T12:00:00Z",
      text: "Ran into Bowser Jr. at the marketplace. He was buying art supplies. We didn't fight - just awkward eye contact. He's just a kid caught up in his father's wars. I feel sorry for him sometimes.",
      userId: "demo-mario",
      inferredMode: "Compassionate",
      inferredEnergy: "Moderate",
      energyShape: "Centered",
      contradiction: "Justice vs. Mercy",
      snapshot: "Unexpected empathy",
      loops: "",
      nextAction: "Consider the child's perspective",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Peaceful encounter with Bowser Jr. sparked empathy",
      actionableInsightsAI: "Enemies may have sympathetic dimensions",
      entryLengthWords: 44,
      daysSinceEntry: 11,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["empathy", "complexity", "enemy"],
      createdTime: "2026-01-01T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-23",
      name: "Mushroom Soup Recipe Success",
      type: "Creativity",
      date: "2026-01-01",
      timestamp: "2026-01-01T18:00:00Z",
      text: "Finally perfected my Super Mushroom soup recipe! The secret is a dash of Fire Flower pepper. Luigi loved it. Cooking is my creative outlet - turning power-ups into power-meals. Maybe I'll write a cookbook.",
      userId: "demo-mario",
      inferredMode: "Satisfied",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Growth vs. Comfort",
      snapshot: "Cooking victory",
      loops: "",
      nextAction: "Try Star-powered dessert",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Perfected cooking recipe with creative ingredients",
      actionableInsightsAI: "Creative hobbies provide balance",
      entryLengthWords: 42,
      daysSinceEntry: 12,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["cooking", "creativity", "satisfaction"],
      createdTime: "2026-01-01T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-24",
      name: "World 8 Planning Session",
      type: "Work",
      date: "2026-01-01",
      timestamp: "2026-01-01T22:00:00Z",
      text: "Spent hours mapping World 8 with Luigi. Every lava pit, every Hammer Bro patrol, every hidden block. This isn't just a rescue - it's a military operation. We will not fail this time. The plan is solid.",
      userId: "demo-mario",
      inferredMode: "Determined",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Action vs. Fear",
      snapshot: "Strategic planning",
      loops: "",
      nextAction: "Execute plan in 3 days",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Detailed strategic planning for World 8 rescue",
      actionableInsightsAI: "Thorough planning reduces failure risk",
      entryLengthWords: 45,
      daysSinceEntry: 12,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["strategy", "teamwork", "planning"],
      createdTime: "2026-01-01T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-25",
      name: "Insomnia Night",
      type: "Health",
      date: "2025-12-31",
      timestamp: "2025-12-31T06:00:00Z",
      text: "Can't sleep. Mind racing about the upcoming mission. What if something happens to Luigi? What if Bowser has new traps? The 3 AM thoughts are always the darkest. Trying breathing exercises.",
      userId: "demo-mario",
      inferredMode: "Anxious",
      inferredEnergy: "Low",
      energyShape: "Chaotic",
      contradiction: "Action vs. Fear",
      snapshot: "Sleepless worry",
      loops: "Anxiety spirals",
      nextAction: "Talk to someone tomorrow",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Pre-mission anxiety causing insomnia",
      actionableInsightsAI: "Practice sleep hygiene before big events",
      entryLengthWords: 40,
      daysSinceEntry: 13,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["insomnia", "anxiety", "worry"],
      createdTime: "2025-12-31T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-26",
      name: "Christmas in the Kingdom",
      type: "Family",
      date: "2025-12-31",
      timestamp: "2025-12-31T12:00:00Z",
      text: "Christmas with the whole crew - Luigi, Yoshi, Toad, Daisy, everyone. We exchanged gifts (I got Luigi new overalls) and played party games. An empty chair for Peach reminded us why we fight. Next year, she'll be here.",
      userId: "demo-mario",
      inferredMode: "Grateful",
      inferredEnergy: "Elevated",
      energyShape: "Expanding",
      contradiction: "Joy vs. Sadness",
      snapshot: "Holiday gathering",
      loops: "",
      nextAction: "Cherish these moments",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Bittersweet Christmas celebration with friends",
      actionableInsightsAI: "Gratitude for present company while honoring absence",
      entryLengthWords: 48,
      daysSinceEntry: 14,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["christmas", "family", "gratitude"],
      createdTime: "2025-12-31T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-27",
      name: "Week 3 Summary",
      type: "Reflection",
      date: "2025-12-31",
      timestamp: "2025-12-31T18:00:00Z",
      text: "Week 3 complete. Had failures (Rainbow Road), breakthroughs (old castle maps), and meaningful connections (Christmas). The mission is set for next week. Fear and hope coexist. That's just how it is.",
      userId: "demo-mario",
      inferredMode: "Reflective",
      inferredEnergy: "Balanced",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Weekly summary",
      loops: "",
      nextAction: "Rest before mission",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Third week reflection with mission anticipation",
      actionableInsightsAI: "Balance preparation with rest",
      entryLengthWords: 38,
      daysSinceEntry: 14,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["reflection", "anticipation", "balance"],
      createdTime: "2025-12-31T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 5 - The Big Mission
    {
      id: "mario-28",
      name: "Mission Day Begins",
      type: "Work",
      date: "2025-12-30",
      timestamp: "2025-12-30T22:00:00Z",
      text: "Today is the day. Packed my power-ups, hugged Luigi, said a prayer. Every step from here on is one step closer to Peach. No more rehearsals. This is real. Let's-a go.",
      userId: "demo-mario",
      inferredMode: "Focused",
      inferredEnergy: "High",
      energyShape: "Rising",
      contradiction: "Action vs. Fear",
      snapshot: "Mission launch",
      loops: "",
      nextAction: "Execute the plan",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Beginning rescue mission with determination",
      actionableInsightsAI: "Trust the preparation and commit",
      entryLengthWords: 39,
      daysSinceEntry: 15,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["mission", "courage", "commitment"],
      createdTime: "2025-12-30T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-29",
      name: "Mid-Castle Crisis",
      type: "Emotional",
      date: "2025-12-30",
      timestamp: "2025-12-30T06:00:00Z",
      text: "Lost my Fire Flower to a surprise Magikoopa. Heart pounding, down to small Mario. Had to hide in a corner for 10 minutes just to breathe. But I kept going. Fear is real. Courage is going anyway.",
      userId: "demo-mario",
      inferredMode: "Anxious",
      inferredEnergy: "Drained",
      energyShape: "Chaotic",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Mid-mission crisis",
      loops: "Crisis management",
      nextAction: "Find power-up, continue",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Crisis moment during mission but persevered",
      actionableInsightsAI: "Pause and breathe during overwhelming moments",
      entryLengthWords: 47,
      daysSinceEntry: 15,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["crisis", "fear", "courage"],
      createdTime: "2025-12-30T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-30",
      name: "Bowser Falls!",
      type: "Work",
      date: "2025-12-30",
      timestamp: "2025-12-30T12:00:00Z",
      text: "CUT THE BRIDGE. BOWSER FELL INTO THE LAVA. Standing before Peach's door, hands shaking, heart full. All those failed attempts, all those 'another castle' moments - they led to this. I did it. WE did it.",
      userId: "demo-mario",
      inferredMode: "Triumphant",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Action vs. Fear",
      snapshot: "Victory moment",
      loops: "",
      nextAction: "Open the door",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Defeated Bowser and reached Peach's door",
      actionableInsightsAI: "Persistence through failure leads to triumph",
      entryLengthWords: 42,
      daysSinceEntry: 15,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["victory", "triumph", "persistence"],
      createdTime: "2025-12-30T12:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-31",
      name: "Reunited with Peach",
      type: "Emotional",
      date: "2025-12-29",
      timestamp: "2025-12-29T18:00:00Z",
      text: "She's safe. She's here. She thanked me and baked a cake (how she baked in captivity is a mystery). We laughed, I cried a little, she pretended not to notice. Best Christmas Eve ever. Thank you, thank you, thank you.",
      userId: "demo-mario",
      inferredMode: "Joyful",
      inferredEnergy: "Elevated",
      energyShape: "Expanding",
      contradiction: "Joy vs. Sadness",
      snapshot: "Reunion moment",
      loops: "",
      nextAction: "Celebrate with everyone",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Emotional reunion with Princess Peach",
      actionableInsightsAI: "Savor moments of achievement fully",
      entryLengthWords: 48,
      daysSinceEntry: 15,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["reunion", "joy", "gratitude"],
      createdTime: "2025-12-29T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-32",
      name: "The Celebration Feast",
      type: "Leisure",
      date: "2025-12-29",
      timestamp: "2025-12-29T22:00:00Z",
      text: "Kingdom-wide celebration! Fireworks, music, dancing Toads. Luigi lifted me on his shoulders. Even Wario showed up (ate most of the cake). Peach addressed the kingdom. For one night, everything was perfect.",
      userId: "demo-mario",
      inferredMode: "Ecstatic",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Victory celebration",
      loops: "",
      nextAction: "Rest and recover",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Kingdom celebrates rescue with grand feast",
      actionableInsightsAI: "Celebrate victories with community",
      entryLengthWords: 39,
      daysSinceEntry: 16,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["celebration", "community", "victory"],
      createdTime: "2025-12-29T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-33",
      name: "Post-Victory Emptiness",
      type: "Reflection",
      date: "2025-12-29",
      timestamp: "2025-12-29T06:00:00Z",
      text: "Strange feeling today. Mission complete, Peach safe, but... now what? So much of my identity was wrapped up in the rescue. Without a crisis, who am I? Need to figure out Mario outside of hero mode.",
      userId: "demo-mario",
      inferredMode: "Lost",
      inferredEnergy: "Low",
      energyShape: "Heavy",
      contradiction: "Purpose vs. Void",
      snapshot: "Identity questioning",
      loops: "Purpose patterns",
      nextAction: "Explore new interests",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Experiencing post-achievement identity crisis",
      actionableInsightsAI: "Identity exists beyond any single role",
      entryLengthWords: 44,
      daysSinceEntry: 17,
      isRecent: true,
      sentimentAI: "Negative",
      themeTagsAI: ["identity", "purpose", "emptiness"],
      createdTime: "2025-12-29T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-34",
      name: "Gardening with Peach",
      type: "Health",
      date: "2025-12-28",
      timestamp: "2025-12-28T12:00:00Z",
      text: "Spent the afternoon gardening in Peach's royal garden. Planting Fire Flowers and Super Mushrooms together, hands in the soil. No enemies, no time pressure. Just growing things. This is nice too.",
      userId: "demo-mario",
      inferredMode: "Peaceful",
      inferredEnergy: "Low",
      energyShape: "Flowing",
      contradiction: "Action vs. Rest",
      snapshot: "Peaceful activity",
      loops: "",
      nextAction: "More gardening",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Quiet gardening time with Peach",
      actionableInsightsAI: "Peaceful activities restore the soul",
      entryLengthWords: 38,
      daysSinceEntry: 17,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["peace", "nature", "connection"],
      createdTime: "2025-12-28T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    // Week 6 - New Beginnings
    {
      id: "mario-35",
      name: "Luigi's New Adventure",
      type: "Family",
      date: "2025-12-28",
      timestamp: "2025-12-28T18:00:00Z",
      text: "Luigi got his own mission call - haunted mansion situation. Watched him leave with his Poltergust 3000, nervous but determined. My little brother is becoming his own hero. So proud. So worried. So proud.",
      userId: "demo-mario",
      inferredMode: "Proud",
      inferredEnergy: "Moderate",
      energyShape: "Rising",
      contradiction: "Closeness vs. Distance",
      snapshot: "Brother's departure",
      loops: "",
      nextAction: "Trust Luigi's growth",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Luigi embarks on solo ghost-hunting mission",
      actionableInsightsAI: "Support others' growth journeys",
      entryLengthWords: 42,
      daysSinceEntry: 18,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["pride", "family", "growth"],
      createdTime: "2025-12-28T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-36",
      name: "Therapy Session with E. Gadd",
      type: "Cognitive",
      date: "2025-12-28",
      timestamp: "2025-12-28T22:00:00Z",
      text: "Professor E. Gadd offered to talk through my post-mission feelings. He's dealt with similar after defeating King Boo. Helpful to know that existential crisis after victory is normal. Not broken, just adjusting.",
      userId: "demo-mario",
      inferredMode: "Understood",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Confidence vs. Doubt",
      snapshot: "Seeking support",
      loops: "",
      nextAction: "Continue check-ins",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Therapeutic conversation about post-victory adjustment",
      actionableInsightsAI: "Seek wisdom from those with similar experiences",
      entryLengthWords: 40,
      daysSinceEntry: 18,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["therapy", "support", "adjustment"],
      createdTime: "2025-12-28T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-37",
      name: "Teaching Young Toads",
      type: "Work",
      date: "2025-12-27",
      timestamp: "2025-12-27T06:00:00Z",
      text: "Started a Hero Training program for young Toads today. Teaching them jumping techniques, power-up usage, basic enemy tactics. Passing on what I know. Maybe the future won't need Mario - and that's okay.",
      userId: "demo-mario",
      inferredMode: "Purposeful",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Growth vs. Comfort",
      snapshot: "Teaching moment",
      loops: "",
      nextAction: "Develop curriculum",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Started hero training program for young Toads",
      actionableInsightsAI: "Legacy is in what we teach others",
      entryLengthWords: 42,
      daysSinceEntry: 19,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["teaching", "legacy", "purpose"],
      createdTime: "2025-12-27T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-38",
      name: "Kart Racing Victory",
      type: "Leisure",
      date: "2025-12-27",
      timestamp: "2025-12-27T12:00:00Z",
      text: "Won the Mushroom Cup! Rainbow Road didn't defeat me this time. Wario tried his dirty tricks but I anticipated every one. Standing on that podium, I realized - I can enjoy competition without it being life or death.",
      userId: "demo-mario",
      inferredMode: "Triumphant",
      inferredEnergy: "High",
      energyShape: "Expanding",
      contradiction: "Competition vs. Collaboration",
      snapshot: "Racing victory",
      loops: "",
      nextAction: "Enter more tournaments",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Won Mushroom Cup kart racing tournament",
      actionableInsightsAI: "Healthy competition builds confidence",
      entryLengthWords: 42,
      daysSinceEntry: 19,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["victory", "competition", "fun"],
      createdTime: "2025-12-27T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-39",
      name: "Bowser Sighting Report",
      type: "Work",
      date: "2025-12-27",
      timestamp: "2025-12-27T18:00:00Z",
      text: "Reports that Bowser survived the lava. Of course he did. But instead of dread, I feel... ready. I know his tricks now. I'm stronger than before. When he comes back, and he will, I'll be here.",
      userId: "demo-mario",
      inferredMode: "Calm",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Action vs. Fear",
      snapshot: "Accepting reality",
      loops: "",
      nextAction: "Maintain readiness",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "News of Bowser's survival met with calm readiness",
      actionableInsightsAI: "Experience transforms fear into preparedness",
      entryLengthWords: 44,
      daysSinceEntry: 20,
      isRecent: true,
      sentimentAI: "Neutral",
      themeTagsAI: ["readiness", "acceptance", "growth"],
      createdTime: "2025-12-27T18:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-40",
      name: "Daisy and Luigi Update",
      type: "Family",
      date: "2025-12-26",
      timestamp: "2025-12-26T22:00:00Z",
      text: "Luigi called - mission successful! He rescued three Toads from King Boo's grasp. Daisy is there to celebrate with him. My heart is full. He found his own courage. The Mario brothers are both heroes now.",
      userId: "demo-mario",
      inferredMode: "Proud",
      inferredEnergy: "Elevated",
      energyShape: "Expanding",
      contradiction: "Closeness vs. Distance",
      snapshot: "Brother's victory",
      loops: "",
      nextAction: "Plan reunion dinner",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Luigi successfully completed his solo mission",
      actionableInsightsAI: "Celebrate others' victories as your own",
      entryLengthWords: 41,
      daysSinceEntry: 20,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["pride", "family", "celebration"],
      createdTime: "2025-12-26T22:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-41",
      name: "New Hobby: Painting",
      type: "Creativity",
      date: "2025-12-26",
      timestamp: "2025-12-26T06:00:00Z",
      text: "Tried painting today. Landscapes of the Mushroom Kingdom. I'm terrible at it - my mushrooms look like blobs. But who cares? Not everything needs to be a heroic skill. Sometimes bad art is still good therapy.",
      userId: "demo-mario",
      inferredMode: "Playful",
      inferredEnergy: "Moderate",
      energyShape: "Flowing",
      contradiction: "Growth vs. Comfort",
      snapshot: "New creative outlet",
      loops: "",
      nextAction: "Keep painting badly",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Started painting as new hobby without pressure",
      actionableInsightsAI: "Allow yourself to be bad at new things",
      entryLengthWords: 43,
      daysSinceEntry: 21,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["creativity", "hobby", "self-compassion"],
      createdTime: "2025-12-26T06:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-42",
      name: "Gratitude Practice",
      type: "Reflection",
      date: "2025-12-26",
      timestamp: "2025-12-26T12:00:00Z",
      text: "What I'm grateful for: Luigi's courage, Peach's safety, Yoshi's friendship, the ability to jump really high, mushroom soup, second chances. Life in the Mushroom Kingdom is wild, but it's my life. And I love it.",
      userId: "demo-mario",
      inferredMode: "Grateful",
      inferredEnergy: "Balanced",
      energyShape: "Centered",
      contradiction: "Joy vs. Sadness",
      snapshot: "Gratitude moment",
      loops: "",
      nextAction: "Daily gratitude practice",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Evening gratitude reflection",
      actionableInsightsAI: "Regular gratitude shifts perspective",
      entryLengthWords: 43,
      daysSinceEntry: 21,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["gratitude", "appreciation", "mindfulness"],
      createdTime: "2025-12-26T12:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-43",
      name: "Week 6 Summary",
      type: "Reflection",
      date: "2025-12-25",
      timestamp: "2025-12-25T18:00:00Z",
      text: "Six weeks of journaling complete. From anxious rescuer to... still anxious, but more aware. Victory happened, emptiness followed, purpose returned. Luigi grew. I grew. Bowser's coming back. But so am I.",
      userId: "demo-mario",
      inferredMode: "Reflective",
      inferredEnergy: "Balanced",
      energyShape: "Centered",
      contradiction: "Growth vs. Comfort",
      snapshot: "Six week reflection",
      loops: "",
      nextAction: "Continue journaling",
      metaFlag: "Demo",
      isSummary: true,
      summaryAI: "Six-week journaling journey summary",
      actionableInsightsAI: "Journaling reveals patterns of growth",
      entryLengthWords: 40,
      daysSinceEntry: 22,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["reflection", "growth", "journey"],
      createdTime: "2025-12-25T18:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
    {
      id: "mario-44",
      name: "Morning Routine Perfected",
      type: "Health",
      date: "2025-12-25",
      timestamp: "2025-12-25T22:00:00Z",
      text: "Meditation, stretching, small breakfast, check pipes in Toad Town, lunch with friends. The routine grounds me. Not every day needs to be epic. Consistency is its own form of heroism.",
      userId: "demo-mario",
      inferredMode: "Grounded",
      inferredEnergy: "Moderate",
      energyShape: "Stabilized",
      contradiction: "Duty vs. Self-Care",
      snapshot: "Routine appreciation",
      loops: "",
      nextAction: "Protect the routine",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Appreciating established daily routine",
      actionableInsightsAI: "Good routines are quiet victories",
      entryLengthWords: 34,
      daysSinceEntry: 22,
      isRecent: true,
      sentimentAI: "Positive",
      themeTagsAI: ["routine", "consistency", "self-care"],
      createdTime: "2025-12-25T22:00:00Z",
      isDeleted: false,
      isBookmarked: false,
    },
    {
      id: "mario-45",
      name: "Looking Forward",
      type: "Reflection",
      date: "2025-12-25",
      timestamp: "2025-12-25T06:00:00Z",
      text: "End of this journaling chapter. What comes next? More castles, probably. More power-ups, definitely. More growth, hopefully. But also more joy, more connection, more being Mario beyond the mustache. Let's-a go.",
      userId: "demo-mario",
      inferredMode: "Hopeful",
      inferredEnergy: "Elevated",
      energyShape: "Rising",
      contradiction: "Past vs. Present",
      snapshot: "Future outlook",
      loops: "",
      nextAction: "Embrace whatever comes",
      metaFlag: "Demo",
      isSummary: false,
      summaryAI: "Optimistic outlook for the future journey",
      actionableInsightsAI: "Face the future with openness",
      entryLengthWords: 40,
      daysSinceEntry: 43,
      isRecent: false,
      sentimentAI: "Positive",
      themeTagsAI: ["hope", "future", "growth"],
      createdTime: "2025-12-25T06:00:00Z",
      isDeleted: false,
      isBookmarked: true,
    },
  ]
}

